### ISSUE TITLE
Wrong indentation of tasklist container resources fails helm chart installations

### ISSUE THREAD

**Issue by taivama** [camunda/camunda-platform-helm#1012]
Resource import in line 125 is indented 10 chars but should be 12 chars to follow proper schema.
https://github.com/camunda/camunda-platform-helm/blob/89523dfba3d5c19303b8ee174c6df17b1c0bb915/charts/camunda-platform/templates/tasklist/deployment.yaml#L125C1-L125C13

This fails the helm installation for Camunda Platfrom 8.3.1 (newest) self-hosted version.

Related:
[SUPPORT-19016](https://jira.camunda.com/browse/SUPPORT-19016)

**Comment by jessesimpson36** [comment]
Thanks for reporting this issue. I confirmed this is a bug.

**Comment by jessesimpson36** [comment]
#1013
