### ISSUE TITLE
Re-assess whether we want multiple postgresql's deployed or not

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#1031]
I think before 8.3, it was a technical necessity to have multiple postgresqls. However, now with 8.3, there were some changes that changes that. 

- We've upgraded keycloak to 22 which uses a newer version of postgresql as a dependency
- We use templates instead of subcharts for most components

**Comment by aabouzaid** [comment]
Based on the team discussion, we will keep PostgreSQL separate to keep the components decoupled.
Yet, it's still possible to configure each PostgreSQL to use a single instance.
