### ISSUE TITLE
[ISSUE] Optimize without Identity tries to connect to C7

### ISSUE THREAD

**Issue by falko** [camunda/camunda-platform-helm#1100]
**Describe the issue:**

When running Optimize without Identity, which AFAIK is not possible, it seems to try to connect to a Camunda 7 engine.

**Actual behavior:**

Optimize produces the following error message, which unfortunately does not reveal what it tries to connect to:
```
16:33:59.244 [PlatformUserIdentityCache-1] ERROR o.c.o.s.util.EngineVersionChecker - Engine didn't respond. Can not verify this engine's version

jakarta.ws.rs.ProcessingException: java.net.ConnectException: Connection refused
```

However, looking at the Optimize source code this `EngineVersionChecker` is related to Camunda 7.

This behavior is likely triggered when the `ccsm` profile is not activated:
https://github.com/camunda/camunda-platform-helm/blob/cb023e69701f220ca7d6f64340d9593a8a9fb7bf/charts/camunda-platform/templates/optimize/deployment.yaml#L81-L83

**Expected behavior:**

1. A clear and concise error message at installation time that Optimize requires Identity in order to work.
2. Optimize does not get installed if Identity is disabled.

**How to reproduce:**

Install Optimize without Identity

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: self-managed Kubernetes + Rancher
- Helm CLI version: 
- Chart version: 8.3.2
- Values file:

**Comment by aabouzaid** [comment]
Thanks @falko, for the suggestion, fixed by #1132 🙌

**Comment by jessesimpson36** [comment]
Issue is present again now that OIDC support is added

**Comment by jessesimpson36** [comment]
related to : https://github.com/camunda/zeebe/issues/16391

**Comment by aabouzaid** [comment]
@jessesimpson36 as I understand, we already fixed that issue, right?

**Comment by jessesimpson36** [comment]
yes
