### ISSUE TITLE
[ISSUE] Cannot access Operate and Tasklist actuator endpoint

### ISSUE THREAD

**Issue by jpan8866** [camunda/camunda-platform-helm#1104]
**Describe the issue:**

I am trying to configure backup for the stack, which requires backing up Operate, Tasklist, Optimize and Zeebe. I am able to reach Optimize and Zeebe through the service host at their respective ports (8092 and 9600). I am unable to reach Operate and Tasklist at port 80, nor do I see a configurable managementPort like there is for Optimize.

**Actual behavior:**

tasklist-svc:80/actuator and operate-svc:80/actuator leads to error 404 - not found

**Expected behavior:**

able to reach /actuator and see list of management endpoints, including /actuator/backups

**Logs:**

error 404 - not found

**Environment:**
OpenShift

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: OpenShift
- Helm CLI version: 3.13.1
- Chart version: 8.3.2

**Comment by jpan8866** [comment]
however i am able to access /actuator through ingress

**Comment by aabouzaid** [comment]
I'm closing this GH issue since it's a misconfiguration.
