### ISSUE TITLE
[ENHANCEMENT] Force identity.auth.enable:true when multinenancy.enable:true

### ISSUE THREAD

**Issue by pierre-yves-monnet** [camunda/camunda-platform-helm#1151]
**Describe the use case:**
When the user moves the cluster to a multi-tenancy, it must set the authentication to true.
Otherwise, we have a cluster in a terra incognita world, and logging/error does not help to figure out what the issue is.

**Describe the enhancement/feature:**

When values.yaml give
`
multinenancy.enable:true
`
then automatically, the helm chart force 
`
identity.auth.enable:true
`

**Desired outcome and acceptance tests:**

**Comment by aabouzaid** [comment]
@pierre-yves-monnet Thanks for reporting that 🙌
We avoid manipulating user input so I've added it to the constraints to fail the installation with a message with instructions to enable the requirements.
