### ISSUE TITLE
[ISSUE] Cannot define resource limitations for the optimize migration container

### ISSUE THREAD

**Issue by lukas-beumer** [camunda/camunda-platform-helm#1212]
**Describe the issue:**

We have very restrictive security and stability settings in our production clusters, which is why we have to define resource limits for each container. This also applies to the initContainers. Unfortunately, we cannot define any resources for the Optimize Migration Container because these cannot be set in these Helm Charts. This also means that we cannot perform clean updates because the migration of the Elasticsearch indicies does not work.

**Actual behavior:**

Currently, no resource limits can be set on the optimize migration container.

**Expected behavior:**

Resource limits can be set on the optimize migration container.

**How to reproduce:**

https://github.com/camunda/camunda-platform-helm/blob/90d058f8a250b418f050a13b714d579583d38c79/charts/camunda-platform/templates/optimize/deployment.yaml#L34

``` 
resources:
  {{- toYaml .Values.optimize.resources | nindent 12 }}
```

**Logs:**

No logs.

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: GCP
- Helm CLI version: v3.12.2
- Chart version: 8.4.0

**Comment by aabouzaid** [comment]
@lukas-beumer thanks for reporting that :+1: 
We plan to work on that before the 8.5 release.

Right now the solution is to disable the migration init container via `optimize.migration.enabled: false` and define yours via `optimize.initContainers`.
