### ISSUE TITLE
[ISSUE] The labels app.kubernetes.io/name for each deployment have changed

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-helm#1222]
**Describe the issue:**

It looks like on the recent releases the `app.kubernetes.io/name` has changed and no longer references the application, as it is recommended https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/ here.

Likely this is related to the refactoring of having one chart. Might be discussable whether camunda-platform is seen as the overarching application, then I guess it makes sense? I just want to highlight that this seems to have changed and discuss whether this was expected.

**Actual behavior:**

Before an Operate deployment had the label: `app.kubernetes.io/name: operate` now it has `app.kubernetes.io/name: camunda-platform`

**Expected behavior:**

We referencing the actual application. 

**How to reproduce:**
Deploy the older and newer charts or check the golden files. https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml#L9

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version:  9.0.1 vs 8.2.5 
- Values file:

**Comment by aabouzaid** [comment]
Hi @Zelldon thanks for reporting that :+1: 

That change has been there since 8.3.x when we moved to this flat-chart structure (except Identity) and we documented it as part of the upgrade process here:
https://docs.camunda.io/docs/self-managed/platform-deployment/helm-kubernetes/upgrade/#v831

**Comment by Zelldon** [comment]
Thanks @aabouzaid yeah we missed some updates in our benchmark helm charts, [which we currently try to update](https://github.com/zeebe-io/benchmark-helm/issues/125) from 8.2.x to 9.x, and I realized this change.

Thanks and good that you aware. I think we close this then.

**Comment by Zelldon** [comment]
Ah BTW @aabouzaid I haven't found the referencing of the labels in the docs, maybe I have overseen this?

**Comment by aabouzaid** [comment]
@Zelldon hmmm, I'm not sure if I get it ... which reference you are looking for? :thinking:
