### ISSUE TITLE
[TASK] Allow defining resources and limits for all components

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#1224]
**Overview:**

The resources and limits for all components in the chart should be configurable (including any side containers like initContainers and ES retention policy containers in 8.1 and 8.2).

**Actions:**

- For all supported versions, review all containers in the chart and ensure that resources and limits are configurable.

**Related Issues:**
- https://github.com/camunda/camunda-platform-helm/issues/354
- https://github.com/camunda/camunda-platform-helm/issues/1212
```[tasklist]
### Tasks
- [ ] [TASK] Add resource limitations for optimize migration container
- [ ] [TASK] Add resource and limits for retention policy containers in 8.2
```

**Comment by lukas-beumer** [comment]
Any updates on this?

**Comment by drodriguez-305** [comment]
Hi @lukas-beumer not yet we are going to start working on this soon. Just moved it to the ready column.
