### ISSUE TITLE
[ISSUE] When using non-default registries, the keycloak initContainer will use the wrong image name

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#1226]
**Describe the issue:**

This issue was found during testing of the AWS Marketplace installation method. the initContainer in keycloak's subchart improperly sets the image name.

```
helm template\
    -f ~/test6/values.yaml \
    -f ~/test6/values-aws.yaml \
    --show-only charts/identity/charts/keycloak/templates/statefulset.yaml \
    charts/camunda-platform | grep -e "image:" -e "name:"
```
Values files linked below

Output:

```
...
          image: '709825985650.dkr.ecr.us-east-1.amazonaws.com/camunda/identity:8.4.0'
          name: copy-camunda-theme
            name: camunda-theme
          image: '709825985650.dkr.ecr.us-east-1.amazonaws.com/camunda/camunda8/keycloak:22.0.5'
          name: copy-configs
            name: config
            name: quarkus
        - name: keycloak
          image: 709825985650.dkr.ecr.us-east-1.amazonaws.com/camunda/camunda8/keycloak:22.0.5
  ...
```

Notice how the identity image should be camunda/camunda8/identity  instead of camunda/identity.  in the values-aws.yaml, we specify a different registry.

**Actual behavior:**

Image name for this initContainer is currently:
```
image: '709825985650.dkr.ecr.us-east-1.amazonaws.com/camunda/identity:8.4.0'
```

**Expected behavior:**

Image name for this initContainer should be 
```
image: '709825985650.dkr.ecr.us-east-1.amazonaws.com/camunda/camunda8/identity:8.4.0'
```

**How to reproduce:**
See top of issue

**Logs:**
ImagePullBackOff

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: AWS Marketplace
- Helm CLI version: 3.11.0
- Chart version: 9.0.2
- Values file: [values-aws.yaml.txt](https://github.com/camunda/camunda-platform-helm/files/13924022/values-aws.yaml.txt)
[values.yaml.txt](https://github.com/camunda/camunda-platform-helm/files/13924023/values.yaml.txt)

**Comment by aabouzaid** [comment]
Fixed by: https://github.com/camunda/camunda-platform-helm/issues/1449

Now it's possible to set the Identity image inside Keycloak via `global.identity.image`.
