### ISSUE TITLE
[ISSUE] operator does not use username/password for rest http to elastic

### ISSUE THREAD

**Issue by gevezex** [camunda/camunda-platform-helm#1235]
**Describe the issue:**
We have a self hosted Elastic cluster with with http (not https) with a username/password for rest. Our self hosted camunda 8 operator does not connect to this http elastic cluster with username password even when these variables are defined:
`camunda.operate.elasticsearch.username`
`camunda.operate.elasticsearch.password`

**Actual behavior:**

Operator connects to elastic without username/password what returns a 401 error (not autorized).

**Expected behavior:**

Should use defined elastic username/password

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: k8s
- Helm CLI version: 3.10.0
- Chart version:  8.4.0

Is there a way to enforce using these defined username/password for elastic http connections?

**Comment by Parth-Shah-99** [comment]
@gevezex Have you tried providing environment variables as below in Operate:
`CAMUNDA_OPERATE_ELASTICSEARCH_USERNAME` & `CAMUNDA_OPERATE_ELASTICSEARCH_PASSWORD`

**Comment by gevezex** [comment]
Thnx @Parth-Shah-99 that helped.
