### ISSUE TITLE
[ISSUE] Missing annotations for Tasklist service

### ISSUE THREAD

**Issue by Parth-Shah-99** [camunda/camunda-platform-helm#1243]
**Describe the issue:**

The Helm Chart does not provide an option to provide/add annotations for Tasklist service.

**Actual behavior:**

Tasklist service takes default annotations.

**Expected behavior:**

Should be able to provide custom annotations to the Tasklist service.

**Note**

The same option is available for other service such as Operate service provides an option to add custom annotations. (Refer #227)

**Comment by aabouzaid** [comment]
Thanks @Parth-Shah-99 for reporting this :+1: 
Fixed by https://github.com/camunda/camunda-platform-helm/pull/1245 and it will be part of the next chart release v9.0.3.
