### ISSUE TITLE
[ISSUE] Replace Zeebee gateway variable with correct Identity configuration properties

### ISSUE THREAD

**Issue by drodriguez-305** [camunda/camunda-platform-helm#1250]
Related to "[SUPPORT-20098](https://jira.camunda.com/browse/SUPPORT-20098)"

**Describe the issue:**

In Zeebe `8.4.0`,  the `identity-spring-boot-autoconfigure`  module was integrated, which provides an `IdentityConfiguration` Spring bean that we pass on to the `identity-sdk` instantiation in the Zeebe Gateway.

- This means that the appropriate environment variables for the [Identity configuration properties](https://docs.camunda.io/docs/next/self-managed/identity/deployment/configuration-variables/) should be automatically picked up by the identity-spring-boot-autoconfigure module.

- It's still possible to use the previous [Zeebe configuration properties for Identity](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/configuration/gateway-config/#zeebegatewayclustersecurityauthenticationidentity).

- The existing [Zeebe configuration properties take precedence](https://github.com/camunda/zeebe/blob/8bac0d4b298394d137b1673c35f7b18e1195a088/gateway/src/main/java/io/camunda/zeebe/gateway/Gateway.java#L338-L346) over the `IdentityConfiguration` bean provided by the identity-spring-boot-autoconfigure  module

As the Zeebe Gateway and Zeebe Broker are both Spring Boot applications, the Spring mechanism for picking up environment variables and setting them to the appropriate configuration properties applies.

**Actual behavior:**

 Zeebe Gateway deployment sets this variable `CAMUNDA_IDENTITY_ISSUERBACKENDURL`. The other components use the config map which sets `CAMUNDA_IDENTITY_ISSUER_BACKEND_URL`
Currently in the Camunda Helm chart we are not using the `CAMUNDA_IDENTITY_ISSUER_BACKEND_URL` environment variable, and using the `CAMUNDA_IDENTITY_ISSUERBACKENDURL` instead.

**Expected behavior:**
The new Identity properties should replace both the Standalone and Embedded Gateway properties since the `IdentityAutoconfiguration` class should provide the same Spring Bean for both

**How to reproduce:**

Suggested fix is to change [`ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_ISSUERBACKENDURL`](https://github.com/camunda/camunda-platform-helm/blob/ec031f27b95eaf56267976484cef3e7571bca0d7/charts/camunda-platform/templates/zeebe-gateway/deployment.yaml#L88) to `CAMUNDA_IDENTITY_BASEURL` this will then be picked up by the `identity-spring-boot-autoconfigure` module.

Confirmed using the Zeebe configuration property `ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_ISSUERBACKENDURL` is a valid workaround, meaning that Spring manages to pick up and map env vars correctly.

**Environment:**
Camunda 8.4 with multitenancy enabled.

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**
- Chart version: 9.0.4

**Comment by garima-camunda** [comment]
Another support ticket raised for this issue - [SUPPORT-20228](https://jira.camunda.com/browse/SUPPORT-20228)

**Comment by koevskinikola** [comment]
To fix the bug, the following needs to be done:

* We need to replace `ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_ISSUERBACKENDURL`  [here](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/templates/zeebe-gateway/deployment.yaml#L88) with `CAMUNDA_IDENTITY_BASE_URL`.
* [These lines](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/templates/zeebe-gateway/deployment.yaml#L90-L91) can be removed, as the Identity env var above will apply for both a Standalone and Embedded Gateway.
* And we need to replace `CAMUNDA_IDENTITY_ISSUERBACKENDURL` [here](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/templates/zeebe-gateway/deployment.yaml#L78) with `CAMUNDA_IDENTITY_ISSUER_BACKEND_URL`.

**Comment by koevskinikola** [comment]
@mschoe it would be good if QA confirms that the bug has been resolved after the fix is merged.
