### ISSUE TITLE
[TASK] Use new Identity SDK config for Connectors

### ISSUE THREAD

**Issue by chillleader** [camunda/camunda-platform-helm#1258]
**Related to:**

https://github.com/camunda/product-hub/issues/1969
https://github.com/camunda/connectors/issues/1638

**Overview:**

Connectors need to be switched to the new Identity SDK config, looking roughly like this:

```
camunda.identity.type=keycloak
camunda.identity.base-url=http://localhost:8084
camunda.identity.issuer=http://localhost:18080/auth/realms/camunda-platform
camunda.identity.issuer-backend-url=http://localhost:18080/auth/realms/camunda-platform
camunda.identity.audience=connectors
camunda.identity.client-id=xxx
camunda.identity.client-secret=xxx
```

**Actions:**

1. Add the new config
2. Remove the old config for authentication with individual components (Zeebe/Operate), as the underlying code now relies on the Identity config.

**Comment by aabouzaid** [comment]
@chillleader does that change require migration steps during the upgrade from the previous version?

**Comment by chillleader** [comment]
@aabouzaid No migration steps required

**Comment by chillleader** [comment]
Done in #1265
