### ISSUE TITLE
[ISSUE] GitHub workflow `test-integration-template` handles the `git-ref` input incorrectly

### ISSUE THREAD

**Issue by chillleader** [camunda/camunda-platform-helm#1275]
**Describe the issue:**

GitHub workflow template `test-integration-template` accepts `git-ref` as an input parameter. But attempting to use it with a custom branch results in an error.

This seems to be caused by the fact that `git-ref` is confusingly used for two different purposes:
1. To check out the Helm charts repository: https://github.com/camunda/camunda-platform-helm/blob/51a2f641f86b8d4ca3f3ce56eb08f70f67d716d3/.github/workflows/test-integration-template.yaml#L101-L105
2. To create a deployment via the `bobheadxi/deployments@v1 ` GHA: https://github.com/camunda/camunda-platform-helm/blob/51a2f641f86b8d4ca3f3ce56eb08f70f67d716d3/.github/workflows/test-integration-template.yaml#L151-L158

This is incorrect, as the first case uses `git-ref` as a ref in the Helm charts repository, while in the second case it is treated as a ref in the repository where the workflow is actually invoked.

See examples:
1. [Failed workflow](https://github.com/camunda/c8-cross-component-e2e-tests/actions/runs/7728463388/job/21069303036) (branch exists in the Helm charts repo, but not in the repository where it's being used)
2. [Successful workflow](https://github.com/camunda/c8-cross-component-e2e-tests/actions/runs/7728713303/job/21070170188) (branch exists in both repositories)

**Actual behavior:**

If the ref doesn't exist in the repository where the workflow is invoked, it fails with the following error:
`Error: unexpected error encountered: HttpError: No ref found for: connectors-support-identity-config - see logs for more information`

**Expected behavior:**

Different inputs should be used for different purposes, e.g. `helm-git-ref` for the Helm charts repo and `git-ref` for the host repo.

**How to reproduce:**

1. Create a GHA workflow in a custom repository that references `test-integration-template`
2. Pass a custom branch name as `git-ref`.

Example workflow: https://github.com/camunda/c8-cross-component-e2e-tests/blob/connectors-support-identity-config/.github/workflows/playwright_sm_manual.yml

**Comment by aabouzaid** [comment]
@jessesimpson36 is that issue in progress?

**Comment by jessesimpson36** [comment]
This is done.
