### ISSUE TITLE
[ISSUE] in version 8.1, connectors component has not been updated

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#1323]
**Describe the issue:**

In the camunda-platform-8.1 release branch, our version for connectors is 0.16.1, which is quite out of date compared to the latest version 0.23.2
https://github.com/camunda/camunda-platform-helm/blob/camunda-platform-8.1/charts/camunda-platform/values.yaml#L1786

in 8.2, we use version 0.23.2: https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values/values-v8.2.yaml#L17

We should check with the connectors team to determine if 8.1 needs to be on 0.16.1, or if 8.1 is compatible with newer versions of connectors.

**Actual behavior:**

**Expected behavior:**

**How to reproduce:**

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:

**Comment by aabouzaid** [comment]
As mentioned by @jessesimpson36, no action is needed here.
