### ISSUE TITLE
[ENHANCEMENT] Modify release process to allow simultaneous releases to occur

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#1349]
**Describe the use case:**

Often times, we have to release a version for 8.1, 8.2, 8.3, and 8.4.  Our scripts / Makefile's `release.chores` will use a branch named `release`, which makes it so that we cannot begin an 8.2 release until 8.1 is already released (if it's in-progress).

If we change it, then one of our team members could release one version each simultaneously, and then it would overall take much less time.

**Describe the enhancement/feature:**

Unsure what implementation would be. I think the release branch name is the only thing forcing us into this synchronous workflow.

**Desired outcome and acceptance tests:**

8.1, 8.2, 8.3, and 8.4 can be released asynchronously.

**Comment by aabouzaid** [comment]
Fixed by: https://github.com/camunda/camunda-platform-helm/pull/1895
