### ISSUE TITLE
[ISSUE] Version matrix does not update if the release is to a backported version (and not latest)

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#1357]
**Describe the issue:**

On a scheduled bugfix release, usually we would release in the following order:
8.1
8.2
8.3
8.4+

And then when 8.4 merges into main, it triggers the "Chart - Public Files" github action which then copies the version matrix from latest main onto the gh-pages branch.  

However during a bugfix release for only backported branches, this file does not get updated in the gh-pages branch because no commit was made to the main branch.

**Actual behavior:**

The version matrix is not updated to show the 8.2.23 version despite it being released.

**Expected behavior:**

The version matrix should be up to date regardless of the kind of release that's happening.

**How to reproduce:**

Release a bugfix onto a backported version, and the matrix will not update.

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:

**Comment by aabouzaid** [comment]
Right now the update happens only in the latest release pipeline (it will update all versions even previous ones).

I've added that to the release process enhancements epic.

We could trigger the matrix build after any release PR, but I'd wait till we are working on the release enhancements epic.

**Comment by aabouzaid** [comment]
Fixed in https://github.com/camunda/camunda-platform-helm/pull/1971 and https://github.com/camunda/camunda-platform-helm/pull/1980
