### ISSUE TITLE
[ISSUE] Zeebe Gateway REST API healthcheck endpoint on 9600 doesn't respond to contextPath changing

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#1392]
**Describe the issue:**

Issue found in this PR,
https://github.com/camunda/camunda-platform-helm/pull/1278

which we decided was not worth investigating as part of that PR. 

If `zeebe-gateway.contextPath` is set to anything other than `/`, the readinessProbes will fail.

We could either:
1. Figure out what env var to change to make the contextPath work. (Note:  the `SERVER_SERVLET_CONTEXT_PATH` and `SPRING_WEBFLUX_BASE_PATH` variables have no effect on the webserver that listens on 9600, however,  the webflux variable does affect the zeebe gateway rest api.
2. Remove the contextPath from the readiness probes (and startup and liveness)

**Actual behavior:**

readiness probes fail if contextPath is changed.

**Expected behavior:**

readinessProbes should succeed if contextPath is changed.

**How to reproduce:**

deploy with contextPath set to zeebe in the gateway, then start a port-forward to 9600 on the zeebe gateway and curl
```
curl -vvvv "http://localhost:9600/zeebe/actuator/health/readiness"
```

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:

**Comment by aabouzaid** [comment]
@npepinpe Does the Zeebe team plan to support the actuator context path?

**Comment by npepinpe** [comment]
It's built into Spring, so it's just a configuration property. Is this something other teams support? If so, we can just align with whatever value they currently support.

**Comment by npepinpe** [comment]
To change the management context path you use `MANAGEMENT_SERVER_BASEPATH=/zeebe` :)

Why is it not aligned with the other var? Trying to figure out why Spring does things the Spring way is sure way to pull your own hair :smile:

**Comment by aabouzaid** [comment]
I will work on this today.
