### ISSUE TITLE
[ISSUE] Our readOnlyRootFilesystem implementation conflicts with the upstream elasticsearch implementation

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#1410]
**Describe the issue:**

This morning, QA and I spotted an issue where CI was failing to schedule any elasticsearch pods.

```
create Pod integration-elasticsearch-master-0 in StatefulSet integration-elasticsearch-master failed error: Pod "integration-elasticsearch-master-0" is invalid: spec.containers[0].
volumeMounts[6].mountPath: Invalid value: "/tmp": must be unique  
```

The /tmp  volumeMount was added to `elasticsearch.extraVolumeMounts` because elasticsearch writes to the /tmp directory, and when enabling the readonlyrootfilesystem, elasticsearch needs that volume. However, the upstream elasticsearch helm chart released a change yesterday (Mar 6, 2024) that  adds the same volume mount.
https://github.com/bitnami/charts/commit/86ee2e8b1dd4f8f449430818d71bef792a771734

We need to identify any other conflicting changes as well from that commit, and adjust our helm chart accordingly.

**Actual behavior:**

elasticsearch pods are not even scheduled and the statefulset automatically scaled itself down to 0 replicas due to an invalid configuration.

**Expected behavior:**

Elasticsearch pods are scheduled and components are capable of connecting to it.

**How to reproduce:**

update the helm chart to use v19.21.0 of the bitnami/elasticsearch helm chart.

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:

**Comment by aabouzaid** [comment]
Fixed by: https://github.com/camunda/camunda-platform-helm/pull/1474
