### ISSUE TITLE
[ISSUE] CI : renovate merged elasticsearch helm chart with breaking changes, and didn't run CI

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#1411]
**Describe the issue:**

Renovate auto-merged this PR yesterday:
https://github.com/camunda/camunda-platform-helm/pull/1404

which breaks existing tests.  When I look on that PR, the only tests that ran was "Update golden files".

We need to investigate why this is, and make sure that Chart.yaml is included in changes that trigger running our integration tests.

I'm switching back to the other related issue:
https://github.com/camunda/camunda-platform-helm/issues/1410

since it has higher priority.

**Actual behavior:**

**Expected behavior:**

**How to reproduce:**

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:

**Comment by aabouzaid** [comment]
Fixed by: https://github.com/camunda/camunda-platform-helm/pull/1474
