### ISSUE TITLE
[ISSUE] Label `app.kubernetes.io/version` does not change when updating Zeebe

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/camunda-platform-helm#1475]
**Describe the issue:**

Updating **only** Zeebe by changing the value of `zeebe.image.tag` does not update the version label of the StatefulSet.
This can be misleading and makes it difficult to verify the results when only upgrading Zeebe and not the other components.

**Actual behavior:**

After the upgrade of Zeebe, the `app.kubernetes.io/version` label still shows the old version.
It seems that only a change of the `global.image.tag` value has an effect on the version label.

**Expected behavior:**

After the upgrade of Zeebe, the `app.kubernetes.io/version` label is updated to the new version.

**How to reproduce:**

```
$ helm install camunda-platform camunda/camunda-platform
$ kubectl get statefulset -l app.kubernetes.io/component=zeebe-broker -L app.kubernetes.io/version
NAME                     READY   AGE     VERSION
camunda-platform-zeebe   1/1     4h39m   8.4.5
$ helm upgrade camunda-platform camunda/camunda-platform --reuse-values --set zeebe.image.tag=8.5.0-alpha2
$ kubectl rollout status -l app.kubernetes.io/component=zeebe-broker
$ kubectl get statefulset -l app.kubernetes.io/component=zeebe-broker -L app.kubernetes.io/version
NAME                     READY   AGE     VERSION
camunda-platform-zeebe   1/1     4h41m   8.4.5 # <- This is wrong, should be 8.5.0-alpha2.
$ helm upgrade camunda-platform camunda/camunda-platform --reuse-values --set global.image.tag=8.5.0-alpha2
$ kubectl rollout status -l app.kubernetes.io/component=zeebe-broker
$ kubectl get statefulset -l app.kubernetes.io/component=zeebe-broker -L app.kubernetes.io/version
NAME                     READY   AGE     VERSION
camunda-platform-zeebe   1/1     4h44m   8.5.0-alpha2 # <- Now it's correct
```

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: version.BuildInfo{Version:"v3.14.3", GitCommit:"f03cc04caaa8f6d7c3e67cf918929150cf6f3f12", GitTreeState:"clean", GoVersion:"go1.21.7"}
- Chart version: camunda-platform-9.3.2
- Values file:

**Comment by aabouzaid** [comment]
@oleschoenburg thanks for reporting this :+1: 

I can reproduce the issue and it comes from this template which uses the sub-chart template syntax, not the flat-chart syntax.

https://github.com/camunda/camunda-platform-helm/blob/45e956a6de5841a5147958aefdc59a8c57dd85e6/charts/camunda-platform/templates/camunda/_helpers.tpl#L54
