### ISSUE TITLE
Use Log4j for operate logging configs

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-helm#148]
It seems that the current logging properties are out dated. I asked for feedback from the operate team. https://camunda.slack.com/archives/C9B5270DA/p1643803696900629

In the deployment guide it seems to reference only the log4j file, so we could do that. https://docs.camunda.io/docs/self-managed/operate-deployment/configuration/#logging

_Originally posted by @Zelldon in https://github.com/camunda-community-hub/camunda-cloud-helm/pull/143#discussion_r797543846_

**Comment by aabouzaid** [comment]
This issue is too old and probably Camunda version is not supported anymore and we haven't gotten any requests about it since then.
