### ISSUE TITLE
[ISSUE] readme CI workflow operates on main rather than PR, sometimes causing main to not have updated readme

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#1497]
**Describe the issue:**

A recent security change we introduced was to prevent github pushes on the main branch. One of the side effects of that change is that this CI workflow that updates the README based off of our values.yaml comments is no longer capable of running because it operates on main and requires permissions to push off main.

HOWEVER,
If you change the github actions workflow to operate just on the pull requests branch, this will flag [an issue in our Github](https://github.com/camunda/camunda-platform-helm/security/code-scanning/68) Security page because in the workflow, it will be reported as an insecure "git clone" because it would need to reference an actual branch instead of the commit hash.

To fix main, we will need to update the readme and then push that to main.

For future CI runs, we will either have to 
1. Ignore the github security notice, and allow the update-readme github actions to operate on the PR branch
2. Selectively allow this CI workflow to pass on main
3. Disable the update-readme workflow (or  make it more manual of a step.)

**Actual behavior:**

CI for update readme workflow fails because main is not properly synchronized.

**Expected behavior:**

CI for update readme workflow  should be capable of running without dependencies on the main branch.

**How to reproduce:**

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:

**Comment by jessesimpson36** [comment]
Daniel included the readme.update command inside the renovate post-action github actions. this will hopefully reduce the occurrences of this problem.

**Comment by jessesimpson36** [comment]
https://github.com/camunda/camunda-platform-helm/pull/1505

**Comment by hamza-m-masood** [comment]
I'm thinking of maybe making a separate commit that only updates the README. Then direct the CI to reference that commit hash instead of the entire PR. Currently not sure if this is possible, or would go against the security changes made.

**Comment by hamza-m-masood** [comment]
Actually, the above is not the best solution since it would still require the user to manually update the readme.

**Comment by hamza-m-masood** [comment]
Another solution would be to add a `readme-update` label on the PR.
When the PR is merged, the `readme-update` workflow can run on the main branch.

**Comment by hamza-m-masood** [comment]
@drodriguez-305 
How viable is it for us to disregard the security notice only for the the `readme-update` workflow and allow it to operate on the PR branch?

**Comment by hamza-m-masood** [comment]
I can also look at how bitnami uses their readme generator in their CI.

**Comment by drodriguez-305** [comment]
From reading this https://github.com/orgs/community/discussions/25305#discussioncomment-8256560 its quite possible we can add the security restrictions with rulesets. Then we can add the distro-ci app to bypass them. Let's discuss next week.

**Comment by drodriguez-305** [comment]
For now I have removed the legacy branch protections and replaced them with rulesets. 

I created two rulesets. From my understanding other users were having problems when using one ruleset with the options enabled so we can try this method of separating it. 

- Default branch (main)- require PR & checks (can be bypass by our Distro -CI apps)
- Default branch (main) - restrict deletions and force push

We can test it out next week.

**Comment by hamza-m-masood** [comment]
I will work with @drodriguez-305 this week to test out the above.

**Comment by hamza-m-masood** [comment]
I didn't find time to work on this issue last week. I will try work on this issue this week.

**Comment by hamza-m-masood** [comment]
Had a meeting with @drodriguez-305 
We saw that only the branch protection rule of not being able to push to main directly effects this workflow. 
We created a [test pr](https://github.com/camunda/camunda-platform-helm/pull/1885) to see if we could get the workflow to push to a new pr instead of the master branch. We were successfully able to do so but then ended up hitting a [security vulnerability](https://github.com/camunda/camunda-platform-helm/security/code-scanning/68).

**Comment by hamza-m-masood** [comment]
In the end we decided with @aabouzaid 's guidance that we will just add a fail message if the user did not manually run the readme generator. 
We decided to go down this route because there is already an existing issue that will automate the readme generator and golden files in this epic.
