### ISSUE TITLE
[ISSUE] How to configure connectors with webhook enabled to run without identity or any kind of authentication

### ISSUE THREAD

**Issue by sayanb19** [camunda/camunda-platform-helm#1554]
I am starting Camunda 8 in EKS self managed way as mentioned in the following links:

- https://docs.camunda.io/docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/eks-eksctl/
- https://docs.camunda.io/docs/self-managed/platform-deployment/helm-kubernetes/platforms/amazon-eks/eks-helm/

I have downloaded helm chart from tag 8.3.3 and changed it locally to enable webhook in connector. Made the change in the following file (https://github.com/camunda/camunda-platform-helm/blob/camunda-platform-8.3.3/charts/camunda-platform/templates/connectors/deployment.yaml) to enable webhook. Removed the "if" condition in environment variable and set:
            - name: CAMUNDA_CONNECTOR_POLLING_ENABLED
              value: "true"
            - name: CAMUNDA_CONNECTOR_WEBHOOK_ENABLED
              value: "true"

Now I am starting the helm chart with the following parameters, but the connector pod is not starting. It is unable to connect to operate at http://localhost:8081.

helm upgrade --install \
  camunda . \
  --version $CAMUNDA_HELM_CHART_VERSION \
  --namespace camunda \
  --create-namespace \
  --set global.ingress.enabled=true \
  --set zeebe-gateway.ingress.enabled=true \
  --set connectors.ingress.enabled=true \
  **--set global.identity.auth.enabled=false \**
  --set operate.contextPath="/operate" \
  --set tasklist.contextPath="/tasklist" \
  --set connectors.contextPath="/connectors" \
  **--set identity.enabled=false \
  --set identity.keycloak.enabled=false \**
  --set optimize.enabled=false \
  --set connectors.inbound.mode=disabled \
  --set zeebe-gateway.service.type=LoadBalancer \
  --set connectors.service.type=LoadBalancer

**How can I configure connectors with webhook enabled to run without identity or any kind of authentication?**

**Comment by jessesimpson36** [comment]
Related: https://github.com/camunda/camunda-platform-helm/pull/1158
https://github.com/camunda/camunda-platform-helm/issues/976

**Comment by jessesimpson36** [comment]
I'm going to continue discussion in #1158  and close this issue.
