### ISSUE TITLE
[TASK] Enforce conventional commits

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#1581]
**Related to:**

Epic: https://github.com/camunda/distribution/issues/234

**Overview:**

Some of the commits are missed in the release notes because they don't follow the exact conventional commits we use in the repo.

So we need to enforce conventional commits that we use only.

**Actions:**

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2089
```

**Comment by hamza-m-masood** [comment]
I have heard that there is a team that has already implemented this feature. I will do a bit of searching to see who has implemented it.

**Comment by hamza-m-masood** [comment]
Identity team uses the PR conventional commits. I used their workflow and modified it a bit.
The PR is ready for review
