### ISSUE TITLE
[ISSUE] upgrade CI workflow will upgrade from the wrong helm chart versions

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#1585]
**Describe the issue:**

During the v10.0.0 helm chart release, we found that  the CI workflow that upgrades between a previous version of the helm chart to a newer version of the helm chart will actually upgrade between 2 identitcal versions of the helm chart:

https://github.com/camunda/camunda-platform-helm/actions/runs/8608080625/job/23629186365

**Actual behavior:**

```
k get -n camunda-platform-pr-1575-run-8608080625-sfx-y0ajxt-upgrade deployment integration-operate -o yaml | yq .metadata.labels

...
helm.sh/chart: camunda-platform-10.0.0
```

Also, heres `helm list` output
```
> helm list -n camunda-platform-pr-1575-run-8608080625-sfx-y0ajxt-upgrade                                                 
NAME       	NAMESPACE                                                 	REVISION	UPDATED                                	STATUS  	CHART                  	APP VERSION
integration	camunda-platform-pr-1575-run-8608080625-sfx-y0ajxt-upgrade	1       	2024-04-09 19:32:15.836004208 +0000 UTC	deployed	camunda-platform-10.0.0	8.4.x
```

**Expected behavior:**

Running the following kubectl command will output the latest minor/patch version from the previous major release. In this case,
(replace the namespace with your own)

```
k get -n camunda-platform-pr-1575-run-8608080625-sfx-y0ajxt-upgrade deployment integration-operate -o yaml | yq .metadata.labels

...
helm.sh/chart: camunda-platform-9.3.3
```

**How to reproduce:**

To observe this, run the upgrade CI workflow in a branch, or rerun the above linked job, and then run `helm list` to view the chart version that gets installed.

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:

**Comment by jessesimpson36** [comment]
I think I misunderstood what the upgrade test was intended for.  This issue should be about how when executing this CI pipeline from a release branch,  for example, 8.3.  The helm chart will install v10.0.2 and then downgrade to 8.3.

The intended upgrade workflow  when it was written was to ensure that upgrading from the latest github release to whatever is in a PR succeeds without any breaking changes.  If we wanted to test upgrades from 8.2 to 8.3, that would be a separate pipeline.

**Comment by aabouzaid** [comment]
This was fixed in: https://github.com/camunda/camunda-platform-helm/pull/1971

Now each Camunda chart version installs the latest chart in that version then try to upgrade it.
For example, this pipeline was a change for Camunda 8.4 and it installed the latest version at that time `9.3.5`
https://github.com/camunda/camunda-platform-helm/actions/runs/9454906174/job/26043707636#step:15:43

then upgrade it from the PR branch:
https://github.com/camunda/camunda-platform-helm/actions/runs/9454906174/job/26043707636#step:18:53
