### ISSUE TITLE
Gateway healthcheck fails [readiness check]

### ISSUE THREAD

**Issue by roshan8** [camunda/camunda-platform-helm#16]
Tried to setup zeebe-cluster using the operator. Everything seems to be working fine except gateway health check.

It's always throwing out_of_service response.
```
{"status":"OUT_OF_SERVICE","components":{"diskSpace":{"status":"UP","details":{"total":21462233088,"free":17460678656,"threshold":10485760,"exists":true}},"gatewayClusterAwareness":{"status":"UP"},"gatewayPartitionLeaderAwareness":{"status":"UP"},"gatewayResponsive":{"status":"UP","details":{"timeOut":"PT0.5S"}},"gatewayStarted":{"status":"UP"},"livenessDiskSpace":{"status":"UP","details":{"total":21462233088,"free":17460678656,"threshold":1048576,"exists":true}},"livenessGatewayClusterAwareness":{"status":"UP","details":{"derivedFrom":"ClusterAwarenessHealthIndicator","wasEverUp":true,"maxDowntime":"PT5M","lastSeenDelegateHealthStatus":{"status":"UP"}}},"livenessGatewayPartitionLeaderAwareness":{"status":"UP","details":{"derivedFrom":"PartitionLeaderAwarenessHealthIndicator","wasEverUp":true,"maxDowntime":"PT5M","lastSeenDelegateHealthStatus":{"status":"UP"}}},"livenessGatewayResponsive":{"status":"UP","details":{"derivedFrom":"ResponsiveHealthIndicator","wasEverUp":true,"maxDowntime":"PT10M","lastSeenDelegateHealthStatus":{"status":"UP","details":{"timeOut":"PT5S"}}}},"livenessMemory":{"status":"UP","details":{"threshold":0.01}},"livenessState":{"status":"UP"},"memory":{"status":"UP","details":{"threshold":0.1}},"readinessState":{"status":"OUT_OF_SERVICE"}},"groups":["liveness","readiness","startup"]}
```

Please refer to this [slack](https://zeebe-io.slack.com/archives/C6WGNHV2A/p1613465496285000?thread_ts=1613111152.238700&cid=C6WGNHV2A) thread

**Comment by Zelldon** [comment]
For reference and to keep history:

@deepthidevaki  wrote

> Usually no. But here it seems it is not using the values configured by default in zeebe. By default gateway health check only includes startup and liveness. But with helm, it is also including readiness, which is not actually available in the gateway. So I assume it is not picking up the right configuration. You can create an issue for it. For now, you could also try to add the proper configurations from here https://github.com/zeebe-io/zeebe/blob/develop/dist/src/main/resources/application.properties to your values.yaml and see if it fixes it.

**Comment by Zelldon** [comment]
Might work now https://github.com/camunda-cloud/zeebe/pull/8506

**Comment by npepinpe** [comment]
Please clarify how the ready and liveness checks work for the gateway.

**Comment by aabouzaid** [comment]
Closing this since readiness/liveness probs have been added and it will be enabled by default in v8.2 (#543)
