### ISSUE TITLE
[ISSUE] Local cluster setup: user permission error when upgrading zeebe

### ISSUE THREAD

**Issue by hamza-m-masood** [camunda/camunda-platform-helm#1602]
**Describe the issue:**

I am running a local cluster: kind
I am using a storageclass that uses rancher. 

I upgraded camunda from `9.3.3` to `10.0.2`
I get the following error in zeebe logs after upgrading:
```
Caused by: java.nio.file.AccessDeniedException: /usr/local/zeebe/data/raft-partition/partitions/1/raft-partition-partition-1.meta
```
**Actual behavior:**

This is a file permission error.
After the upgrade to `10.0.2`, the userID in zeebe is `1000`. This user tries to access the file `/usr/local/zeebe/data/raft-partition/partitions/1/raft-partition-partition-1.meta` which is previously configured with userID `1001` before the upgrade.
This crashes the zeebe pod.
This error occurs because my local cluster has a storageClass that does not support fsGroup.
**Expected behavior:**

I expect userID `1000` to successfully access the above file in zeebe.
**How to reproduce:**

setup a kind cluster with the following storageclass:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"},"name":"standard"},"provisioner":"rancher.io/local-path","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"}
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2024-04-11T01:06:02Z"
  name: standard
  resourceVersion: "267"
  uid: 846c555f-9211-40b1-b62a-431cea4a3b4e
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
Install camunda helm version `9.3.3` and upgrade to `10.0.2`
**Logs:**

```
Caused by: java.nio.file.AccessDeniedException: /usr/local/zeebe/data/raft-partition/partitions/1/raft-partition-partition-1.meta
```
**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: local kind cluster
- Helm CLI version: 3.14.3
- Chart version: 10.0.2
- Values file: default

**Comment by aabouzaid** [comment]
We have docs to deal with this situation: https://docs.camunda.io/docs/self-managed/operational-guides/update-guide/830-to-840/#dockerfile-numeric-id

The rest of the storage providers will work smoothly using what we provide in the `fsGroup` in our values file.
