### ISSUE TITLE
[ISSUE] Default values.yaml (no ingress) identity fails with http://   IDENTITY_URL v9.3.2

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#1604]
**Describe the issue:**
When using the default values.yaml,  identity, connectors, tasklist, and operate will all fail due to a misconfiguration where identity fails to connect to keycloak.  This misconfiguration was traced to the variable `IDENTITY_URL` not being set.  Because Identity cannot connect to keycloak without this environment variable being set,   the other pods which connect to keycloak can no longer authenticate, causing them to crashloop as well.

[SUPPORT-21272](https://jira.camunda.com/browse/SUPPORT-21272)

Workaround (add this to your values.yaml):
```
identity:
  env:
    - name: IDENTITY_URL
      value: http://localhost:8080
```

Check newest 9.3.3 + latest 10.0.2

**Actual behavior:**
Identity, operate, and tasklist crashloop

**Expected behavior:**
When no values.yaml is supplied, it's expected that all of the pods should come up as Ready and Running. Using port-forwards to each of the pods should also work.

**How to reproduce:**

Install with no values.yaml and observe crashing pods.
```
helm install camunda camunda/camunda-platform --version 9.3.2
```

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: KIND
- Helm CLI version: v3.11
- Chart version: 9.3.2 (may impact newer charts too)
- Values file: default values (no values.yaml file)

**Comment by hamza-m-masood** [comment]
Why not just add the url in the values.yaml as default as I have it in the above PR? 
Have a look :)

**Comment by hamza-m-masood** [comment]
Also this is a duplicate or an issue I create before:
https://github.com/camunda/camunda-platform-helm/issues/1589

**Comment by jessesimpson36** [comment]
I am closing this issue because it is a duplicate.
