### ISSUE TITLE
Tasklist not connecting to ElasticSearch after upgrade to 8.5.0

### ISSUE THREAD

**Issue by fjakop** [camunda/camunda-platform-helm#1611]
After upgrading from 8.3.0 to 8.5.0 Tasklist is no longer able to connect to ElasticSearch. The logfile states

    i.c.t.e.ElasticsearchConnector           : Retrying #49 connect to Elasticsearch at http://localhost:9200 due to ElasticsearchException[java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused]; nested: ExecutionException[java.net.ConnectException: Connection refused]; nested: ConnectException[Connection refused];
    i.c.t.e.ElasticsearchConnector           : Retries 50 exceeded for connect to Elasticsearch at http://localhost:9200

and then the pod terminates.

In version 8.3.0 this was running as expected.

The application.yaml of tasklist is

    # Tasklist configuration file
    camunda.tasklist:
      # Set Tasklist username and password.
      # If user with <username> does not exists it will be created.
      # Default: demo/demo
      #username:
      #password:
      # ELS instance to store Tasklist data
      elasticsearch:
        # Cluster name
        clusterName: elasticsearch
        # Host
        host: camunda8-elasticsearch
        # Transport port
        port: 9200
      # Zeebe instance
      zeebe:
        # Broker contact point
        brokerContactPoint: "camunda8-zeebe-gateway:26500"
      # ELS instance to export Zeebe data to
      zeebeElasticsearch:
        # Cluster name
        clusterName: elasticsearch
        # Host
        host: camunda8-elasticsearch
        # Transport port
        port: 9200
        # Index prefix, configured in Zeebe Elasticsearch exporter
        prefix: zeebe-record
    #Spring Boot Actuator endpoints to be exposed
    management.endpoints.web.exposure.include: health,info,conditions,configprops,prometheus,loggers,usage-metrics,backups
    # Enable or disable metrics
    #management.metrics.export.prometheus.enabled: false

**Environment:**

- Platform: Rancher 2 v2.7.6
- Helm CLI version: v3.14.2
- Chart version: app.kubernetes.io/component : tasklist app.kubernetes.io/name : tasklist app.kubernetes.io/part-of : camunda-platform app.kubernetes.io/version : 8.5.0 helm.sh/chart : tasklist-8.3.0

Values file: 

    global:
      image:
        tag: 8.5.0
      identity:
        auth:
          publicIssuerUrl: "https://camunda8-keycloak.redacted.domain/auth/realms/camunda-platform"
          connectors:
            existingSecret: camunda8-connectors-identity-secret
          operate:
            existingSecret: camunda8-operate-identity-secret
            redirectUrl: "https://operate.redacted.domain"
          optimize:
            existingSecret: camunda8-optimize-identity-secret
            redirectUrl: "https://optimize.redacted.domain"
          tasklist:
            existingSecret: camunda8-tasklist-identity-secret
            redirectUrl: "https://tasklist.redacted.domain"
          webModeler:
            redirectUrl: "https://modeler.redacted.domain"
    elasticsearch:
      extraEnvs:
        - name: "cluster.routing.allocation.disk.watermark.low"
          value: "96%"
        - name: "cluster.routing.allocation.disk.watermark.high"
          value: "97%"
        - name: "cluster.routing.allocation.disk.watermark.flood_stage"
          value: "98%"
        - name: "cluster.routing.allocation.disk.watermark.flood_stage.frozen"
          value: "98%"
        - name: "xpack.security.enabled"
          value: "false"
    identity:
      # FirstUser configuration to configure properties of the first Identity user, which can be used to access all
      # web applications
      firstUser:
        username: demo
        password: demo
        email: demo@example.org
        firstName: Demo
        lastName: User
      fullURL: https://identity.redacted.domain
      ingress:
        enabled: true
        host: identity.redacted.domain
        tls:
          enabled: true
          secretName: "my-tls-secret"
      keycloak:
        extraEnvVars:
          # see https://jira.camunda.com/browse/SUPPORT-13836
          - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
            value: "true"
        ingress:
          # If `true`, an Ingress is created
          enabled: true
          hostname: 'camunda8-keycloak.redacted.domain'
          # List of rules for the Ingress
          extraTls:
            - hosts:
                - 'camunda8-keycloak.redacted.domain'
              secretName: "my-tls-secret"
    operate:
      env:
        - name: CAMUNDA_OPERATE_ENTERPRISE
          value: "true"
      ingress:
        enabled: true
        host: operate.redacted.domain
        tls:
          enabled: true
          secretName: "my-tls-secret"
    optimize:
      env:
        - name: CAMUNDA_OPTIMIZE_ENTERPRISE
          value: "true"
      ingress:
        enabled: true
        host: optimize.redacted.domain
        tls:
          enabled: true
          secretName: "my-tls-secret"
    postgresql:
      enabled: true
    tasklist:
      env:
        - name: CAMUNDA_TASKLIST_ENTERPRISE
          value: "true"
      ingress:
        enabled: true
        host: tasklist.redacted.domain
        tls:
          enabled: true
          secretName: "my-tls-secret"
    webModeler:
      enabled: true
      image:
        pullSecrets:
          - name: "registry-camunda-cloud"
      ingress:
        enabled: true
        webapp:
          # Note: the value must be different from ingress.websockets.host
          host: "modeler.redacted.domain"
          tls:
            enabled: true
            secretName: "my-tls-secret"
        websockets:
          # Note: the value must be different from ingress.webapp.host
          host: "websockets.redacted.domain"
          tls:
            enabled: true
            secretName: "my-tls-secret"
      restapi:
        mail:
          smtpHost: smtp.redacted.domain
          smtpPort: 587
          #smtpUser: user
          #smtpPassword: secret
          # email address to be displayed as sender of emails from Web Modeler
          fromAddress: "no-reply@camunda8.redacted.domain"
    zeebe-gateway:
      ingress:
        enabled: true
        host: "zeebe.redacted.domain"
        tls:
          enabled: true
          secretName: "my-tls-secret"
    zeebe:
      env:
        - name: ZEEBE_BROKER_DATA_SNAPSHOTPERIOD
          value: "5m"
        - name: ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK
          value: "0.96"
        - name: ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK
          value: "0.98"

**Comment by aabouzaid** [comment]
@fjakop You need to upgrade the chart itself.
The Helm chart 8.3.x will not with Camunda 8.5 apps.
Use [Helm chart v10.0.2](https://github.com/camunda/camunda-platform-helm/releases/tag/camunda-platform-10.0.2) or above.

And probably you will need to upgrade to Camunda apps 8.4 first.

**Comment by fjakop** [comment]
@aabouzaid thanks, that was it.
