### ISSUE TITLE
[ISSUE] Zeebe Gateway SERVER_PORT is using the incorrect port (affects readiness probes)

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#1616]
**Describe the issue:**

During the switch to application-style configurations for each component, we accidentally changed the SERVER_PORT (or `server.port`)  option to the Zeebe gateway REST API port rather than the normal port (9600). This does not normally matter, since both the zeebe gateway rest api  port and the 9600 port should both have actuator endpoints, however, there are some install-flows that are affected.  Those who use version 8.5 (helm 10.0.2) along with v8.4.6 of zeebe will experience readiness probe failures due to the REST API port not being available on 8.4.6 of zeebe. 

The application teams have informed us that they do not want us referring to the REST API endpoint for readiness probes, so it should be changed back.

**Actual behavior:**

Readiness probes fail for zeebe-gateway pod on v10.0.2  with 8.4.6 of zeebe gateway.

**Expected behavior:**

Readiness probes should succeed for  zeebe-gateway pod.

**How to reproduce:**

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:

**Comment by aabouzaid** [comment]
I'm closing this issue since that case is not supported (Camunda 8.4 cannot be used with chart v10.x.x since it supports Camunda 8.5 only).

```
helm search repo camunda/camunda-platform --versions | head -n 5
NAME                    	CHART VERSION	APP VERSION	DESCRIPTION                                       
camunda/camunda-platform	10.0.2       	8.5.x      	Camunda 8 Self-Managed Helm charts. Camunda's p...
camunda/camunda-platform	9.3.3        	8.4.x      	Camunda 8 Self-Managed Helm charts. Camunda's p...
camunda/camunda-platform	9.3.2        	8.4.x      	Camunda 8 Self-Managed Helm charts. Camunda's p...
camunda/camunda-platform	9.3.1        	9.3.x      	Camunda 8 Self-Managed Helm charts. Camunda's p...
```
