### ISSUE TITLE
zeebe-operate-helm and zeebe-tasklist-helm doesnot allow toleration and podSelector values in values.yaml

### ISSUE THREAD

**Issue by nareshgoswami1508** [camunda/camunda-platform-helm#163]
Hi, 
I wanted to deploy all pods related to Zeebe in a different node pools in AKS. I figured it out that I can run all the pods in one node pool except the tasklist and operate pods.
Is there anyway to set these values for Tasklist and operate pods?

I have used below values.yaml file for installing the zeebe-full-helm chart.

helm upgrade --namespace zeebe --install --wait --timeout 10m0s zb zeebe/zeebe-full-helm -f values.yaml

`
global:
  zeebe: "{{ .Release.Name }}-zeebe"

zeebe-cluster-helm:
  elasticsearch:
    tolerations:
    - key: "zeebe"
      operator: "Equal"
      value: "gpu"
      effect: "NoSchedule"
    nodeSelector:
      zeebe: isolatenodepool
  gateway:
    tolerations:
    - key: "zeebe"
      operator: "Equal"
      value: "gpu"
      effect: "NoSchedule"
    nodeSelector:
      zeebe: isolatenodepool

  tolerations:
  - key: "zeebe"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
  nodeSelector:
    zeebe: isolatenodepool

cloudevents:
  enabled: false
tasklist:
  enabled: true
zeeqs:
  enabled: false 

ingress-nginx:   
  controller:
    tolerations:
    - key: "zeebe"
      operator: "Equal"
      value: "gpu"
      effect: "NoSchedule"
    nodeSelector:
      zeebe: isolatenodepool
    service:
      ports:
        http: 80
        https: 443
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"

zeebe-tasklist-helm:
  ingress:
    enabled: true
    annotations:
      ingress.kubernetes.io/ingress.class: nginx
      ingress.kubernetes.io/rewrite-target: "/"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"    
    path: /
    host: tasklist.zeebe.weud
    tls:
      enabled: false
      secretName:
  nodeSelector:
    zeebe: isolatenodepool
  tolerations:
  - key: "zeebe"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"

zeebe-operate-helm:
  ingress:
    enabled: true
    annotations:
      ingress.kubernetes.io/ingress.class: nginx
      ingress.kubernetes.io/rewrite-target: "/"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"    
    path: /
    host: operate.zeebe.weud
    tls:
      enabled: false
      secretName:
  nodeSelector:
    zeebe: isolatenodepool
  tolerations:
  - key: "zeebe"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
`

result in AKS cluster:
![image](https://user-images.githubusercontent.com/64729907/152861273-6acbdd4a-61bc-47a8-ad2d-5a19d6322a51.png)

**Comment by Zelldon** [comment]
Done via #257
