### ISSUE TITLE
[TASK] Make use of the `gatewayAddress` property instead of the deprecated `brokerContactPoint` in Operate

### ISSUE THREAD

**Issue by romansmirnov** [camunda/camunda-platform-helm#1646]
**Related to:**

With https://github.com/camunda/zeebe/issues/17062, Operate is distributed together with Zeebe as a Single JAR (Distribution). By that, the Operate configuration is part of the `application.yaml` file and no longer in `application.yml` (without an `a` in `yaml`). Additionally, a while ago the configuration property `brokerContactPoint` was marked as deprecated, and instead the property `gatewayAddress` must be used.

All that together, it may cause Operate to try to connect to Zeebe via `localhost:26500`, which is caused by the order Spring loads/applies the `application.yml` and `application.yaml` files. Plus, how Operate sets the `gatewayAddress` (even when using the `brokerContactPoint`), see https://github.com/camunda/zeebe/pull/17571

While this will be fixed in Operate itself, I suggest adjusting the config map accordingly to reflect the changes in the Helm Charts as well. 

**Overview:**

- [ ] In Operate, use `gatewayAddress` instead of `brokerContactPoint`
- [ ] In Operate, change `application.yml` to `application.yaml` to be mounted

**Actions:**

- This change must be released with 8.6.0.

**Comment by romansmirnov** [comment]
Opened a PR to apply the changes: https://github.com/camunda/camunda-platform-helm/pull/1647

**Comment by aabouzaid** [comment]
@romansmirnov Thanks for the issue and the PR.
Should it be part of the 8.6 "cycle" (before October) or the 8.6 "release" (in October)?
