### ISSUE TITLE
[ENHANCEMENT] Make templating in values.yaml possible when setting host, replicas, storageClass and pvc size (different settings for different environments with same values.yaml)

### ISSUE THREAD

**Issue by igor-msk** [camunda/camunda-platform-helm#1648]
**Describe the use case:**
Use different values for host, replicas, storageClass and pvc size without separate values.yaml files for each envorinment.

**Describe the enhancement/feature:**

treat the corresponding values as {{ tpl .Values.xxx . }} instead of simply {{ .Values.xxx }}

**Desired outcome and acceptance tests:**

Example:
```
global.ingress.host: "{{ .Values.global.environment }}-camunda.your-domain.com"
global.identity.keycloak.url.host: "{{ .Values.global.environment }}-keycloak.your-domain.com"

connectors.replicas: "{{ if eq .Values.global.environment \"Dev\" }} 1 {{ else }} 2 {{ end }}"
zeebeGateway.replicas: "{{ if eq .Values.global.environment \"Dev\" }} 1 {{ else }} 2 {{ end }}"

zeebe.pvcStorageClassName: "{{ if eq .Values.global.environment \"Dev\" }}csi-disk-topology{{ else }}local-storage{{ end }}"
zeebe.pvcSize: "{{ if eq .Values.global.environment \"Dev\")  }}5Gi{{ else }}32Gi{{ end }}"
```

```[tasklist]
### Tasks
```

**Comment by aabouzaid** [comment]
@igor-msk thanks for the idea, but we will not support that style since it will increase the complexity of the chart.
You can use different values files for different envs and load the conditionally.
