### ISSUE TITLE
[TASK] Update Zeebe entrypoint to use config file instead of env vars

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#1659]
**Related to:**

PR: https://github.com/camunda/camunda-platform-helm/pull/1597

**Overview:**

Currently, the Zeebe entry point script overrides the network config and we need to use the env vars which is a snowflake compared to the other config.

**Actions:**

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda-platform-helm/pull/1910
```

**Comment by hamza-m-masood** [comment]
Trying to see if I can replicate the error of not being able to port forward the zeebe gateway pod.

**Comment by hamza-m-masood** [comment]
issue created: https://github.com/camunda/camunda/issues/19114

**Comment by hamza-m-masood** [comment]
PR created in zeebe repo: https://github.com/camunda/camunda/pull/19132

**Comment by aabouzaid** [comment]
@hamza-m-masood Anything else is needed for this task?
