### ISSUE TITLE
[TASK] Configure Operate's management port to check readiness

### ISSUE THREAD

**Issue by romansmirnov** [camunda/camunda-platform-helm#1661]
**Related to:**

With https://github.com/camunda/zeebe/issues/17062, Operate and Zeebe share the same Spring configuration. This means now Operate also opens a management port on `9600`.

**Overview:**

Ensure that the management port is used to check Operate's liveness (like readiness, ...).

**Actions:**

- [ ] Configure `managementPort` in `deployment.yml`
- [ ] Use `managementPort` in `readinessProbe`, `startupProbe`, and `livenessProbe`
- [ ] Configure the `context-path` accordingly
- [ ] Adjust `service.yml` configuration to map `managementPort`
- [ ] Adjust Operate's `service-monitor.yml` settings
- [ ] Provide option to configure management port (default `9600`)

**Comment by aabouzaid** [comment]
@romansmirnov Thanks for open this task :raised_hands: 
What is the target version for this change? will it be part of 8.5.x or it's for 8.6?
