### ISSUE TITLE
[TASK] Support dnsPolicy and dnsConfig in all components

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#1678]
**Related to:**

Epic: https://github.com/camunda/distribution/issues/230

**Overview:**

We need to add `dnsPolicy` and `dnsConfig` which allows [configuring the DNS for the Pod](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/).

**Comment by drodriguez-305** [comment]
just need to add the unit test.
