### ISSUE TITLE
[TASK] Review official docs guides and ensure that they match the current state

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#1680]
**Related to:**

Epic: https://github.com/camunda/distribution/issues/230

**Overview:**

Some of the guides in our [official docs](https://docs.camunda.io/) are not updated with the latest changes we have in the Helm chart.
We need to review and update the [guides](https://docs.camunda.io/docs/self-managed/setup/guides/).

**Examples:**
- [Combined and separated Ingress setup](https://docs.camunda.io/docs/self-managed/setup/guides/ingress-setup/): It doesn't have Console and Connectors.

**Comment by hamza-m-masood** [comment]
@drodriguez-305 Now that there is a rest endpoint on zeebe gateway, might be a good idea to update the diagram on this doc: https://docs.camunda.io/docs/self-managed/platform-architecture/overview/
Since it only references a GRPC endpoint. But not sure if we want to go that far 😄 seems like kind of time consuming.

**Comment by hamza-m-masood** [comment]
@drodriguez-305 the config for this guide is wrong I think: https://docs.camunda.io/docs/self-managed/setup/guides/using-existing-keycloak/

It should be `identityKeycloak`

**Comment by drodriguez-305** [comment]
> @drodriguez-305 the config for this guide is wrong I think: https://docs.camunda.io/docs/self-managed/setup/guides/using-existing-keycloak/
> 
> It should be `identityKeycloak`

This is fine as its talking about an existing keycloak.

> @drodriguez-305 Now that there is a rest endpoint on zeebe gateway, might be a good idea to update the diagram on this doc: https://docs.camunda.io/docs/self-managed/platform-architecture/overview/ Since it only references a GRPC endpoint. But not sure if we want to go that far 😄 seems like kind of time consuming.

yeah true maybe we can save this one for another time.

> @drodriguez-305 For example, this doc: https://docs.camunda.io/docs/self-managed/setup/guides/ingress-setup/ uses `https` links without configuring tls. This is a non-working example and would have to be reworked in my opinion.

I can possibly add a note that tls is configured on this example.
