### ISSUE TITLE
[ISSUE] With Zeebe Gateway context path specified console reports unhealthy zeebe gateway despite being healthy in kubectl describe

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#1789]
**Describe the issue:**
We are experiencing an issue where the readiness, liveness, and startup probe paths configured in the Zeebe Gateway are not reflecting the required contextPath. This omission leads to Kubernetes probes failing, which incorrectly marks the Zeebe Gateway pods as unhealthy in console SM.

![2024-05-13-131328_grim](https://github.com/camunda/camunda-platform-helm/assets/19277629/2efb5810-0e2d-4bb7-b970-c89d040b47cc)

![2024-05-13-131453_grim](https://github.com/camunda/camunda-platform-helm/assets/19277629/a3c351ea-dea9-4062-9db0-6ef881deec0d)

**Actual behavior:**
The contextPath is not being prepended to the actuator paths in the configuration, resulting in probe paths like `/actuator/health/readiness` without the necessary prefix. This configuration causes the probes to fail as the paths do not correctly resolve to the health endpoints.

**Expected behavior:**
The Zeebe Gateway's probes for readiness, liveness, and startup should include the contextPath as a prefix to the actuator paths to correctly point to the health check endpoints. For example, if contextPath is set to `/zeebe`, the readiness probe path should be `/zeebe/actuator/health/readiness`.

**How to reproduce:**
1. Set up the Camunda Platform Helm chart with the following values:
`zeebeGateway.contextPath` to `"/zeebe"`
2. Deploy Helm charts
3. Observe that the readiness, liveness, and startup probes for the Zeebe Gateway pods fail due to incorrect paths in console SM. 
4. Check console configmap and see that `/zeebe` is missing 

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:

**Comment by drodriguez-305** [comment]
I updated the description of the issue. This is related to https://jira.camunda.com/browse/SUPPORT-21751
