### ISSUE TITLE
policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+

### ISSUE THREAD

**Issue by falko** [camunda/camunda-platform-helm#18]
k8s 1.21 says: **policy/v1beta1** PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use **policy/v1** PodDisruptionBudget

**Comment by Zelldon** [comment]
I migrated out zeebe gke cluster to 1.21. It makes sense now to update the manifests

**Comment by npepinpe** [comment]
Please check with Felix on what the support cadence should be for us - should we follow Kubernetes', or do we have data of our own that would inform another choice?

**Comment by Zelldon** [comment]
See https://camunda.slack.com/archives/CHBFBRFM2/p1656322979043949?thread_ts=1656074129.033929&cid=CHBFBRFM2

**Comment by aabouzaid** [comment]
I will close this issue since we updated `PodDisruptionBudget` for all our resources.
