### ISSUE TITLE
[ISSUE] zeebe and connectors existingSecret.name create warning messages

### ISSUE THREAD

**Issue by drodriguez-305** [camunda/camunda-platform-helm#1809]
**Describe the issue:**

When using connectors or zeebe with `global.identity.auth.connectors.existingSecret.name` users will encounter a warning message. Secrets are working as expected but the warnings are triggered.

```
global:
  identity:
    auth:
      connectors:
        existingSecret: 
          name: dev-identity-secrets
      zeebe:
        existingSecret: 
          name: dev-identity-secrets
      
```
The warnings that get triggered are the following

```
coalesce.go:289: warning: destination for camunda-platform.global.identity.auth.zeebe.existingSecret is a table. Ignoring non-table value ()
coalesce.go:289: warning: destination for camunda-platform.global.identity.auth.connectors.existingSecret is a table. Ignoring non-table value ()
```

In our main default values file connectors and zeebe have `existingSecret: ""` which is the main culprit of triggering the warning.  This is because of helm logic. 

```
      connectors:
        ## @param global.identity.auth.connectors.clientId defines the client id, which is used by Connectors in authentication flows.
        clientId: connectors
        ## @param global.identity.auth.connectors.existingSecret can be used to use an own existing secret. If not set a random secret is generated.
        # The existing secret should contain an `connectors-secret` field, which will be used as secret for the identity-Connectors communication.
        existingSecret:""
```

**Actual behavior:**
When setting `global.identity.auth.connectors.existingSecret.name` or `global.identity.auth.zeebe.existingSecret.name` will trigger the warnings.

**Expected behavior:**
Setting those should not cause any warnings as other components do not trigger them.

**How to reproduce:**
Set `global.identity.auth.connectors.existingSecret.name` or `global.identity.auth.zeebe.existingSecret.name` and run the helm installation.

Quick fix is to remove the empty strings from `global.identity.auth.connectors.existingSecret` and `global.identity.auth.zeebe.existingSecret` in our default values file. Once they are removed you can run a helm template or a helm install without triggering the warnings.

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 9.x.y, 10.x.y 
- Values file: 
- Related to: https://jira.camunda.com/browse/SUPPORT-21718

**Comment by hisImminence** [comment]
Related to https://github.com/helm/helm/pull/12812
