### ISSUE TITLE
[ENHANCEMENT] Proposal to deprecate separated ingresses (combined ingress as only pre-configured option)

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#1838]
**Describe the use case:**

With the emphasis being placed on Camunda being a single product with a unified api, rather than a collection of components, I wonder if it makes sense to have one ingress that all the components use. If we standardized on one way to connect to each of the components, then our helm chart and documentation would be significantly simpler because we wouldn't be writing versions for combined ingress vs separated ingress, it'd just be one of those.

And part of this complexity is situations where we need to supply external urls into each component for links, such as the URLs we generate for the Console component (that we currently get from `helm status`).  

**Describe the enhancement/feature:**

**Desired outcome and acceptance tests:**

**Comment by theburi** [comment]
Hi. As we discussed at different forums. Lets announce this deprication in alpha5.
Target to depricate separate ingress in 8.7

**Comment by hisImminence** [comment]
The announcement should be posted in the:
* blog-post
* Release notes
* Add comment into value.yml
* Announcement page in docs (@conceptualshark please report back)

**Comment by conceptualshark** [comment]
@hisImminence Suggestion for docs updates:
- Add a notice to the [combined and separated Ingress docs](https://docs.camunda.io/docs/next/self-managed/setup/guides/ingress-setup/) in /next, noting the planned 8.7 deprecation
- When deprecated, update the [announcement page](https://docs.camunda.io/docs/reference/announcements/) for 8.7

**Comment by hisImminence** [comment]
Thanks for the quick response! Sounds good to me!

**Comment by jessesimpson36** [comment]
https://github.com/camunda/camunda-docs/pull/4195

this is merged, which should cover all the points brought up so far, however, there is one more PR that needs made, to add a comment in values.yaml.

**Comment by jessesimpson36** [comment]
I added comments in our values.yaml  . The documentation side of this proposal is complete, however,  before closing out this task, we should probably open a github issue for the actual removal of the separated ingress options and schedule it for 8.7

**Comment by jessesimpson36** [comment]
We can now close this ticket since we have the new task for removal of this functionality in 8.7
