### ISSUE TITLE
Add configMap defaultMode to helm chart values file

### ISSUE THREAD

**Issue by felix-mueller** [camunda/camunda-platform-helm#184]
**Please describe the missing/desired functionality:**

Provide a mechanism to override defaulMode value using values.yaml

|volumes:|
||- name: config
||configMap:|
||name: {\{ include "zeebe-cluster.fullname" . }}|
||{color:#FF0000}*defaultMode: 0744*{color}|

**What problem would the feature solve?**

After deployment containers cant read configMap because they are running as non-root

**What effort would be required without the feature?**

Since we're running containers as non-root, after each deploy we have to change this value manually in yaml.

**Why do you need this feature?**

Because it's inconvenient to change this value after each deployment

 **How would not implementing the feature impact you?**

We need to change yaml file manually after each helm upgrade or install.

**Support**
https://jira.camunda.com/browse/SUPPORT-12967

**Comment by jonathanlukas** [comment]
Same issue here: https://jira.camunda.com/browse/SUPPORT-13290

**Comment by McAlm** [comment]
What @jonathanlukas and the customer proposed is not working for another partner on open shift. They get the same initial error and tried to fix with the mentioned defaultMode, but get:
`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.containers[0].volumeMounts[0]): unknown field "defaultMode" in io.k8s.api.core.v1.VolumeMount`
This aligns with `kubectl explain StatefulSet --recursive=true | grep volumeMounts -A10 -B1` which gives no occurence of this attribute...

**Comment by Zelldon** [comment]
Hey @McAlm it is part of the volumnes spec


![volumne](https://user-images.githubusercontent.com/2758593/161282377-a0441528-b644-4e26-9473-f6d43d6fbf2a.png)
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#volume-v1-core

**Comment by falko** [comment]
OpenShift converts the value from octal to integer representation. But setting `0755` works to get Zeebe started.

**Comment by Zelldon** [comment]
Hey folks, @falko @McAlm @jonathanlukas with #277 we solved this issue (hopefully) we made the defaultMode for configMaps for all services configurable. **Example** for Zeebe would be: `zeebe.configMap.defaultMode=0755` 

I will create an release now so you can try it out and tell it our customers.
