### ISSUE TITLE
[ISSUE] Unavailable endpoint for livenessProbe of zeebe brokers

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda-platform-helm#1849]
**Describe the issue:**

The latest helm chart uses a non-existing endpoint for `livenessProbe` for Zeebe brokers. It uses `actuator/health/liveness` which is not exposed in Zeebe. You can see the available endpoints [here](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/operations/health/)

**Actual behavior:**

When livenessProbe is enabled, pods crash loop because the endpoint returns `404`

**Expected behavior:**

There is no crashloop when livenessProbe is enabled.

**Environment:**

Openshift v4.14, C8 SM, Helm Charts v10.0.5

More info in [support ticket](https://jira.camunda.com/browse/SUPPORT-22030)

**Comment by deepthidevaki** [comment]
I see that [this commit](https://github.com/camunda/camunda-platform-helm/commit/edc2e96b1bf9cfc110c77007737a0cf8b1817714#diff-2506cdbfd5f03488f145ec7829301a08c868b00822e9d0c6a797158a2e061ab4) added the non existing liveness endpoint in the helm charts. 

I see two options:

1. Revert it to the previous `/health` (which might be now `actuator/health/status`)
2. Remove livenessProbe for zeebe brokers entirely

I prefer option 2 because Zeebe brokers do not expose a meaningful endpoint for liveness check. Using the health status is not ideal because it returns unhealthy even if it is only partially unhealthy. Kubernetes restarts the pods if liveness probe is not successful. We may not always want to restart a pod just because it is temporarily unhealthy. /cc @npepinpe for a second opinion from zeebe side.

**Comment by npepinpe** [comment]
We can also align it with SaaS, and use the readiness endpoint as well. It means if the node is never ready, it will be restarted. It doesn't help if it ever becomes ready, since we don't update the status, but it can still help a little bit initially.

Here are the probes in SaaS:

```
    Liveness:   http-get http://:9600/actuator/health/readiness delay=0s timeout=1s period=15s #success=1 #failure=22
    Readiness:  http-get http://:9600/actuator/health/readiness delay=0s timeout=1s period=5s #success=1 #failure=3
    Startup:    http-get http://:9600/actuator/health/startup delay=0s timeout=1s period=10s #success=1 #failure=75
```
