### ISSUE TITLE
[ISSUE] Can't reference an existing secret for `global.identity.auth.identity.existingSecret`

### ISSUE THREAD

**Issue by hamza-m-masood** [camunda/camunda-platform-helm#1857]
**Describe the issue:**

Currently, it is not possible to reference an existing secret for identity like so:
```yaml
global:
  identity:
    auth:
      identity:
        existingSecret:
          name: "testSecret"
```

Only the value of the secret can be provided in the values.yaml.

**Actual behavior:**

When you attempt to add a `name` key under `existingSecret` you get the following output in the identity configmap:
```
data:
  application.yaml: |
    identity:
      client-secret: "map[name:testSecret]"
```
For this reason, if it is not intended to create functionality to reference an existing secret using the `name` value, then at least there should be a check to ensure that the `existingSecret` value is a string.

This secret is only needed when you configure external OIDC
A clear comment should be mentioned in the vaues.yaml to make it clear to customers that this secret is only needed for external OIDC
**Expected behavior:**

I expect to reference an existing secret using the `name` value under `existingSecret` for identity and have it rendered correctly.

**How to reproduce:**

use the values.yaml I provided at the top.

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: GKE
- Helm CLI version: 3.15
- Chart version: 10.0.4
- Values file:

**Comment by Boboltus** [comment]
I have the exact same issue/request. Only I would like to see it solved for all the secrets in the Helm chart and not just the one mentioned here (Identity). In addition to that it would be nice if you could reference the name of the existing secret's key. For example, when using the `identityPostgresql` there is an option called 'secretKeys/userPasswordKey' where you can specify the name of the key. That would allow us to integrate more easily with existing Kubernetes Secrets.

**Comment by j-lindner** [comment]
Addition: 
When you set the identity secret (for EntraID or other generic OIDC) with a string value, like global.identity.auth.identity.existingSecret: EasySecret, this gets inject in clear in Identities configmap/application.yaml.

Snippet from ConfigMap **camunda-identity-configuration**:


│ Data                                                                                                                                                                                                                                                                       │
│ ====                                                                                                                                                                                                                                                                       │
│ application.yaml:                                                                                                                                                                                                                                                          │
│ ----                                                                                                                                                                                                                                                                       │
│ identity:                                                                                                                                                                                                                                                                  │
│   url: "https://jensil.de/identity"                                                                                                                                                                                                                                        │
│   client-id: "identity"                                                                                                                                                                                                                                                    │
│   client-secret: "EasySecretInPlainText"

**Comment by jonathanlukas** [comment]
Workaround if you don't want to expose your secret values in the values.yaml:

```yaml
identity:
  env:
  - name: CAMUNDA_IDENTITY_CLIENTSECRET
     valueFrom:
       secretKeyRef:
         name: camunda-secrets
         key: identity-secret
```
This will override the `camunda.identity.client-secret` from the identity `application.yaml` and allow referencing a secret.
