### ISSUE TITLE
[ENHANCEMENT] Camunda Optimize connection with AWS Opensearch using IRSA

### ISSUE THREAD

**Issue by Sivajey** [camunda/camunda-platform-helm#1966]
Hello Team,

We are currently testing Camunda in our development environment and are aiming to enhance our setup for production using AWS Opensearch Service. We've noticed that most of Camunda's components support connecting to Opensearch using IRSA, with the exception of Optimize and it needs username and password https://docs.camunda.io/docs/self-managed/setup/deploy/amazon/amazon-eks/irsa/#amazon-opensearch-service

Could you kindly provide any information on when Optimize might support this functionality?

Thanks

**Comment by jessesimpson36** [comment]
@camunda/optimize , @grlimacan    Can you link a camunda/optimize ticket for supporting IRSA in AWS?

**Comment by grlimacan** [comment]
> @camunda/optimize , @grlimacan Can you link a camunda/optimize ticket for supporting IRSA in AWS?

There you go: https://github.com/camunda/camunda-optimize/issues/12696

**Comment by grlimacan** [comment]
or if you prefer the public issue: https://github.com/camunda/issues/issues/739

**Comment by aabouzaid** [comment]
I'm going to close this issue since there is already a feature request for the Optimize team.
