### ISSUE TITLE
[ENHANCEMENT] In existingSecrets warning/error message, suggest base64 encoded autogenerated password instead of a placeholder

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#1976]
**Describe the use case:**

Part of https://github.com/camunda/product-hub/issues/1957

**Describe the enhancement/feature:**

**Desired outcome and acceptance tests:**

**Comment by aabouzaid** [comment]
My idea was actually to generate the secret file once using a values file flag + Helm hooks as disturbed here:
https://github.com/camunda/camunda-platform-helm/issues/1983

**Comment by aabouzaid** [comment]
No need to do anything else, given now we provide a way to auto-gen passwords as in https://github.com/camunda/camunda-platform-helm/issues/1983
