### ISSUE TITLE
[ISSUE] identityKeycloak does not have an ingressClassName value

### ISSUE THREAD

**Issue by hamza-m-masood** [camunda/camunda-platform-helm#2019]
**Describe the issue:**

There should be a following key in the values.yaml:
`identityKeycloak.ingress.ingressClassName `
Currently it does not exist.

Adding the above value would not  conform with our current naming standard. All ingress classes are specified using the `className` value, not `ingressClassName`. For example:
`identity.ingress.className`

**Expected behavior:**

Have a value in the values.yaml that specifies the ingress class name for keycloak.

**Comment by aabouzaid** [comment]
Given it's not consistent between Bitnami charts (e.g. [Bitnami PostgreSQL chart](https://artifacthub.io/packages/helm/bitnami/postgresql) doesn't have it), I'd say we don't have much to do about it (especially we refer to the Keycloak values docs anyway).
