### ISSUE TITLE
[ISSUE] Optimize: Should perform rolling update with downtime

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/camunda-platform-helm#2026]
**Describe the issue:**

Optimize should not perform a rolling uptime with 2 instances running in parallel

**Actual behavior:**

Due to the current `RollingUpdateStrategy`, there might be 2 pods up at the same time:

```
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
```
**Expected behavior:**

There is no concurrent 2 optimize pods on update.

**How to reproduce:**

Install the helm chart with optimize enabled.

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: not relevant
- Helm CLI version: not relevant
- Chart version: latest
- Values file: no values required

**Comment by aabouzaid** [comment]
This will be fixed by https://github.com/camunda/camunda-platform-helm/issues/2035

**Comment by jessesimpson36** [comment]
Implemented and merged in https://github.com/camunda/camunda-platform-helm/pull/2036
