### ISSUE TITLE
[TASK] Set deployment strategy for all components

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#2035]
**Describe the use case:**

Users need to set the deployment strategy like in https://github.com/camunda/camunda-platform-helm/issues/2026

**Desired outcome and acceptance tests:**

- [ ] Add a new section for all deployment objects to configure `spec.strategy`.
- [ ] No behavior change for all components and should be nulled, except for Optimize which should use the `Recreate update strategy`.

**Comment by jessesimpson36** [comment]
Implemented and merged in #2036
