### ISSUE TITLE
AWS Opensearch basic auth secrets

### ISSUE THREAD

**Issue by rohits123** [camunda/camunda-platform-helm#2128]
Is this a bug ? 
global.opensearch.auth.existingSecret and global.opensearch.auth.password both cannot be set ? 

https://github.com/camunda/camunda-platform-helm/blob/2a334ba4eb16f0e46a6bfcf2791e03fc64b5a6dd/charts/camunda-platform-latest/templates/operate/deployment.yaml#L56C11-L56C99

**Comment by hamza-m-masood** [comment]
I just created an issue for this using our issue template: https://github.com/camunda/camunda-platform-helm/issues/2133
I will close this issue and work on the problem as soon as I have some time. Thanks for reporting!
