### ISSUE TITLE
[ISSUE] Duplicate `spec.strategy`

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/camunda-platform-helm#2153]
**Describe the issue:**

On some templates, there are multiple `spec.strategy` fields, for example here:

https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform-latest/templates/operate/deployment.yaml#L11-L12

https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform-latest/templates/operate/deployment.yaml#L14-L17

**Actual behavior:**

I fear that as soon as `operate.strategy` is set, the template will not work anymore.

**Expected behavior:**

This meaningful default should be part of the values.yaml

**How to reproduce:**

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: k8s
- Helm CLI version: irrelevant
- Chart version: 10.2.1
- Values file: `operate.strategy.type: Recreate`

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2155
```

**Comment by hamza-m-masood** [comment]
After discussing with my team I will do the following:

I will remove the `strategy` option from the operate and tasklist components in the values.yaml for the latest version (8.5). I will have to check with the teams if this option can be kept in the alpha version.

**Comment by hamza-m-masood** [comment]
I asked both teams if the rolling update could be possible in 8.6

**Comment by hamza-m-masood** [comment]
I can confirm that operate will not support rolling update in 8.6 release. So I will make the same change for operate in the alpha version.
Reference: https://camunda.slack.com/archives/C9B5270DA/p1722237321400769?thread_ts=1722010893.157929&cid=C9B5270DA

**Comment by hamza-m-masood** [comment]
I will also make the same change for optimize

**Comment by hamza-m-masood** [comment]
UPDATE:
We will rollback the feature of configuring the deployment strategy. I have created a new issue for this and am currently working on the PR:
https://github.com/camunda/camunda-platform-helm/issues/2160
