### ISSUE TITLE
[ISSUE] non-TLS installations identity cannot be accessed under a subpath

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#2182]
**Describe the issue:**

When installing the helm chart using `http` for all components under an ingress, the user will fail to log in to identity with a  javascript popup that reads 

> "Identity cannot be accessed under a sub-path. Please use the latest Chrome, Firefox or Edge browser and make sure you are not in an incognito/private tab or window."

![2024-08-05-155749_grim](https://github.com/user-attachments/assets/934d5cf2-db61-449b-aeba-7e517d012764)

This may be an identity issue, since I can't find anything in the chart that I'd configure to get around this.

**Actual behavior:**

**Expected behavior:**

**How to reproduce:**

**Logs:**

[identity.log.txt](https://github.com/user-attachments/files/16502194/identity.log.txt)

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: KIND
- Helm CLI version: v3.15.3
- Chart version: 10.2.1
- Values file:  
[base-combined-http.yaml.txt](https://github.com/user-attachments/files/16502187/base-combined-http.yaml.txt)

**Comment by jessesimpson36** [comment]
Identity team confirmed that this is as a result of the identity application making use of service workers
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API

which requires an HTTPS connection.

**Comment by jessesimpson36** [comment]
Identity team also shared that on a separated ingress, HTTP connections should work due to there not being a contextpath for identity.

**Comment by aabouzaid** [comment]
It's a known issue since Identity implemented the `contectPath`, and here are more details about the issue [Identity contextPath](https://docs.camunda.io/docs/next/self-managed/operational-guides/troubleshooting/#identity-contextpath).

Given we have the docs for it and it's not something we can fix in Helm, I close this issue.
