### ISSUE TITLE
Add readiness check for operate

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-helm#219]
Currently we support no readiness check for operate, which means it becomes immediately ready, even if elastic is not available yet. This means user might try to access operate but it will fail. Related also to IT where we need the readiness for better testing. #215

**Comment by Zelldon** [comment]
See https://docs.camunda.io/docs/self-managed/operate-deployment/configuration/#monitoring-operate

**Comment by aabouzaid** [comment]
Closing this since it's now added and it will be enabled by default in v8.2 (#543)
