### ISSUE TITLE
[ENHANCEMENT] Enable Play by default in Web Modeler

### ISSUE THREAD

**Issue by huygur** [camunda/camunda-platform-helm#2256]
**Describe the use case:**

Play should be accessible from Web Modeler 

**Describe the enhancement/feature:**

Web Modeler's webapp image accepts the following environment variable

**PLAY_ENABLED**

When set to true, Play tab is visible to users next to Design/Implement tabs.

**Desired outcome and acceptance tests:**

⚠️ Should be merged after Web Modeler 8.6-alpha5 release
When flag is enabled, Play tab should be visible in Web Modeler

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda-platform-helm/pull/2269
```

**Comment by sephiroth-j** [comment]
@hamza-m-masood: Now it's impossible to disable it. Adding the env `PLAY_ENABLED` to ``webModeler.webapp.env` will result in two env-entries with the same name which is not allowed.
