### ISSUE TITLE
Align cpu/io thread count with partition count

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-helm#226]
We increased the partition count to three, but left the cpu/io thread count untouched. This means they are still on 2. We could either raise it to 3 or bump it to 1 since the resources are so low.

**Comment by deepthidevaki** [comment]
My suggestion here is to set the default cpuThreadCount to 3 (=partitioncCount). But keep the i/o threadcount at 2. i/o threads are only used by exporters. So we don't need so many i/o threads. But cpuThreads are used by several actors with in a single partition itself. So it helps to have more cpuThreads to distribute the work. 

@Zelldon wdyt?

**Comment by Zelldon** [comment]
I often try to have similar values, for simplicity. But, I guess this is fine since we anyway have fewer resources and the web apps are currently not able to keep up with Zeebe, so I guess less pressure via exporting would be fine. If the user wants more performance he can set it, we can also increase the number later if we see issues with it. 

Do you think it makes sense to set such a value in SaaS then as well? I think we currently haven't adjusted them for a while.

**Comment by deepthidevaki** [comment]
> Do you think it makes sense to set such a value in SaaS then as well? I think we currently haven't adjusted them for a while.

I think it makes sense to adjust if we see any problems. May be once Roman is done with the performance targets we can revisit them and adjust if needed.

Are we trying to keep the configs of helm charts and SaaS in sync?

**Comment by Zelldon** [comment]
> Are we trying to keep the configs of helm charts and SaaS in sync?

Yes we try that our defaults are similar the the S plan

**Comment by deepthidevaki** [comment]
> > Are we trying to keep the configs of helm charts and SaaS in sync?
> 
> Yes we try that our defaults are similar the the S plan

In that case, I would use the current configs from S plan. We can discuss later if the config of S plan should be adjusted or not.
