### ISSUE TITLE
[ISSUE] Upgrade helm charts to support Keycloak v25 

### ISSUE THREAD

**Issue by drodriguez-305** [camunda/camunda-platform-helm#2270]
**Describe the issue:**
Keycloak has deprecated their hostname v1 options. 

https://github.com/bitnami/charts/blob/HEAD/bitnami/keycloak/CHANGELOG.md#2210-2024-08-06 we need to implement hostname v2 options  https://www.keycloak.org/docs/latest/upgrading/index.html#migrating-to-25-0-0 there is no way to set `path` or `port` separately. We will need to provide the full URL for `hostname`

**Actual behavior:**
Keycloak is broken in alpha.

**Expected behavior:**

**How to reproduce:**

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:

**Comment by jessesimpson36** [comment]
I think you may have forgotten to run 
```bash
helm dependency update ./charts/camunda-platform-alpha
```

**Comment by jessesimpson36** [comment]
I'm closing this because I have a setup right now that works with keycloak v25.
