### ISSUE TITLE
[ISSUE] New constraints in 8.3.2 cause errors with default values

### ISSUE THREAD

**Issue by lukas-beumer** [camunda/camunda-platform-helm#2272]
**Describe the issue:**

Since 8.3.2, a constraint has been introduced that checks whether the value from `.Values.zeebeGateway.ingress.rest.path` is the same as the value from `.Values.zeebeGateway.contextPath`.

However, the default value for .`Values.zeebeGateway.ingress.rest.path` is `“/”` by default, whereas the default value for `.Values.zeebeGateway.contextPath` is `“”`, which of course corresponds to an inequality. 

Technically, however, these values are correct, because as soon as no contextPath is used for the Zeebe Gateway, it must also remain empty. If this contextPath is also set to “/”, this leads to double slashes in the Helm Chart.

https://github.com/camunda/camunda-platform-helm/blob/b54fa13a1de20e2ae54c143449fcd11dbec85afa/charts/camunda-platform-latest/templates/camunda/constraints.tpl#L66

**Actual behavior:**

If the REST endpoint of the Zeebe Gateway is activated, the Helm template cannot be templated because the constraint does not allow this due to the different values as described above.

In principle, however, the constraint would be correct if the two values did not correspond to the default values, but not in the default case.

**Expected behavior:**

The constraint does not fail if the values are left in the standard.

**How to reproduce:**

```
zeebeGateway:
    ingress:
      rest:
        enabled: true
```

Environment:

Platform: GCP
Helm CLI version: v3.15.4
Chart version: 10.3.2

**Comment by aabouzaid** [comment]
I'd still need to get a confirmation from @camunda/zeebe team if that's expected from the app side or not.
We can fix it from the Helm side with a workaround, but it could indicate a deeper issue.

Also related to #2282

**Comment by npepinpe** [comment]
I'm afraid I don't get what you mean by "if that's expected from the app side". We definitely should not have a double `/`, that will be interpreted incorrectly.

**Comment by aabouzaid** [comment]
This issue has been fixed in https://github.com/camunda/camunda-platform-helm/issues/2282 and it will be part of the next release.
