### ISSUE TITLE
Zeebe operate and tasklist affinity and podLabels rules

### ISSUE THREAD

**Issue by mihneastaub** [camunda/camunda-platform-helm#228]
Hi @Zelldon ,

It will not be good to add also the podLabels and affinity rules for the zeebe operate and tasklist? If this will be approved than I can create the pr for this change.

**Comment by Zelldon** [comment]
Makes sense to me @mihneastaub please make sure to read https://github.com/camunda/camunda-platform-helm/blob/main/CONTRIBUTING.md before creating a PR :)

**Comment by Zelldon** [comment]
Thanks for your contribution #257 released with https://github.com/camunda/camunda-platform-helm/releases/tag/camunda-platform-8.0.4
