### ISSUE TITLE
[ISSUE] Identity first user has no permissions - 8.6 alpha5

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#2339]
**Describe the issue:**

> [!NOTE]
> We found that the issue happens with and without multi-tenancy enabled.

If you try to authenticate to identity, you will be redirected to `/unauthorized`, which in a typical installation with Console on the base path, means that `/unauthorized` will be redirected to Console, and then you will see a 404 or 401 error.

the endpoint it redirects to might actually be `/noPermissions`. I'm forgetting. 

To work around this issue, log into Keycloak and inside the `camunda-platform` realm, go to Users > demo > Role mapping and assign all of the role mappings to the first user, and you will get access to identity once more.

![2024-09-11-151710_grim](https://github.com/user-attachments/assets/8fcbfe96-7e09-4c29-893b-b8fed554768c)

**Actual behavior:**

**Expected behavior:**

**How to reproduce:**

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 8.6.0-alpha5
- Values file:

**Comment by jessesimpson36** [comment]
https://github.com/camunda/distribution/issues/306

**Comment by jessesimpson36** [comment]
I just learned that this issue affects separated ingress as well, but not on combined ingress.

**Comment by jessesimpson36** [comment]
I just learned that this issue affects separated ingress (without multitenancy enabled) as well, but not on combined ingress.

**Comment by drodriguez-305** [comment]
upon further testing yesterday its also affecting combined ingress. Also tested with multitenancy disabled and combined ingress with the same results.

**Comment by aabouzaid** [comment]
My investigation led to nothing, and I've asked the Identity team to take a look (in the `ask-identity` channel).

@andromaqui Do you use the [Distro GHA workflow](https://github.com/camunda/camunda-platform-helm/blob/main/docs/gha-workflows.md)? For some reason, it doesn't happen with that setup (when an extra user is added).

If not, you can use that workaround to move forward ... here is what we use:
https://github.com/camunda/camunda-platform-helm/blob/0ae40cc0b50b516187714a1d6ab0b91bb2063ff3/charts/camunda-platform-alpha/test/integration/scenarios/common/values-integration-test.yaml#L3
