### ISSUE TITLE
[ISSUE] Console configures it's own readiness probe to be HTTP  even when the app is configured  for HTTPS

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#2376]
**Describe the issue:**

When configuring TLS on the pod level, it is possible for the kubernetes readiness probes to make HTTPS requests instead of HTTP requests by setting the `console.readinessProbe.scheme`, but console itself is an entity that makes requests to other pods healthcheck endpoints. It is those requests that are hardcoded to be HTTP instead of HTTPS.

Variable we should be using:
https://github.com/camunda/camunda-platform-helm/blob/0ae40cc0b50b516187714a1d6ab0b91bb2063ff3/charts/camunda-platform-alpha/values.yaml#L500

Where we want the readiness url to be:
https://github.com/camunda/camunda-platform-helm/blob/0ae40cc0b50b516187714a1d6ab0b91bb2063ff3/charts/camunda-platform-alpha/templates/console/configmap.yaml#L26

Where it's hardcoded to HTTP
https://github.com/camunda/camunda-platform-helm/blob/0ae40cc0b50b516187714a1d6ab0b91bb2063ff3/charts/camunda-platform-alpha/templates/camunda/_helpers.tpl#L564-L570

CC: @Szik  (reported the issue)

**Actual behavior:**

**Expected behavior:**

**How to reproduce:**

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:

**Comment by hamza-m-masood** [comment]
Keycloak section does not need to be modified because the external ingress URL is grabbed:
https://github.com/camunda/camunda-platform-helm/blob/0ae40cc0b50b516187714a1d6ab0b91bb2063ff3/charts/camunda-platform-alpha/templates/camunda/_helpers.tpl#L251
