### ISSUE TITLE
[ENHANCEMENT] Remove default resource limits from Helm charts

### ISSUE THREAD

**Issue by kam-uddin** [camunda/camunda-platform-helm#2444]
**Describe the use case:**

For most of the services provided by Camunda’s Helm chart a CPU resource limits is set per default (e.g. https://github.com/camunda/camunda-platform-helm/blob/bab9b2a5cd4ec7e8daeaf5fa0089ba858ec6c0b9/charts/camunda-platform-latest/values.yaml#L2169). Meanwhile this is known as an antipattern since the limit is also applied if the underlying node is idle. Maybe you want to rethink setting limits

**Describe the enhancement/feature:**

Modify helm charts to remove default resource limits

**Desired outcome and acceptance tests:**

Remove default resource limits

As per the customer's suggestion in the ticket https://jira.camunda.com/browse/SUPPORT-23728?focusedCommentId=374175&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-374175

**Comment by aabouzaid** [comment]
@kam-uddin Thanks for opening this issue.
We will not make this change, as it's best practice to have a default value for requests and limits.

Still, the user is able to override those numbers or unset them by setting them to null.

E.g.
```
zeebe:
  resources:
    requests:
      cpu: null
      memory: null
    limits:
      cpu: null
      memory: null
```
