### ISSUE TITLE
HELM Template 0.0.27 not working with attached error

### ISSUE THREAD

**Issue by inghak** [camunda/camunda-platform-helm#253]
Error: INSTALLATION FAILED: template: ccsm-helm/charts/identity/templates/deployment.yaml:30:30: executing "ccsm-helm/charts/identity/templates/deployment.yaml" at <include "common.names.dependency.fullname" (dict "chartName" "keycloak" "chartValues" .Values.keycloak "context" $)>: error calling include: template: no template "common.names.dependency.fullname" associated with template "gotpl"

**Comment by Zelldon** [comment]
Thanks for reporting will fix it tomorrow

**Comment by Zelldon** [comment]
Is fixed with https://github.com/camunda/camunda-platform-helm/commit/ea161f9cbcc0417e8fbac3e8a6e02a76f75f509b and new release is available (0.0.28) sorry for any inconvenience this made to you. :bow:
