### ISSUE TITLE
Enabled TLS between identity and keycloak

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-helm#256]
With #127 we added Identity to the charts. Per default TLS is not enabled for the authentication (communication between keycloak and identity).

We should investigate how we could enable the TLS setting. It seems that we either need to bring a certificate or keycloak can create a self-signed cert. 

https://github.com/bitnami/charts/blob/master/bitnami/keycloak/values.yaml#L144-L203

**Comment by aabouzaid** [comment]
I'm closing this issue since it's out of the scope of the default setup and we found that many users use a Service Mesh to fix handle that out of the Helm config.
