### ISSUE TITLE
[TASK] Adjust resources defaults for the unified Core deployment

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#2583]
**Describe the use case:**

In 8.7-alpha, we introduced a new "core" deployment type which will combine zeebe, operate, and tasklist . However, we still have the same resource requests and limits that zeebe had before despite it needing to respond to operate and tasklist requests and perform the steps that the operate importer and exporter would normally do.

**Describe the enhancement/feature:**

I would suggest we take the requests and limits for each application, and add them together for our new requests and limits for the core deployment.  I would be open for other suggestions as well for what those requests and limits should be.

One minor concern I have about bumping these numbers up is that this may prevent scheduling the core deployment on nodes that do not meet the requests.  So any solution we come up with for this issue should take that into account.

**Desired outcome and acceptance tests:**

**Comment by Zelldon** [comment]
Please see https://zeebe-io.github.io/zeebe-chaos/2024/11/14/Impact-of-Camunda-Exporter-on-processing-performance/ for some input in sizing
