### ISSUE TITLE
enhancement request

### ISSUE THREAD

**Issue by fvogl** [camunda/camunda-platform-helm#260]
Hi

If possible and time permits please add configurable podAnnotations, imagePullSecrets and affinity to charts/operate/deployment.yaml.
Also if you could make the config volume defaultMode configurable for the charts/zeebe/statefulset.yaml it would safe me from changing this chart before using it.

Thanks, Friedrich

**Comment by Zelldon** [comment]
Hey @fvogl 

thanks for the feedback.

You can now configure the configMap defaultMode, done via #277

**Comment by Zelldon** [comment]
I split your request into two more feature requests https://github.com/camunda/camunda-platform-helm/issues/303 https://github.com/camunda/camunda-platform-helm/issues/302 and will close this issue.
