### ISSUE TITLE
[ENHANCEMENT] Provide an optional prefix for the Standalone Camunda application (used in ES/OS)

### ISSUE THREAD

**Issue by ChrisKujawa** [camunda/camunda-platform-helm#2610]
**Describe the use case:**

When using the (new) Camunda Exporter you can choose as backend between Elasticsearch and Opensearch. The Camunda Exporter will store the data in the respective backends under certain indices, these indices can be prefixed, such that potentially multiple SM installations can be deployed and ES or OS instances can be reused. 

**Describe the enhancement/feature:**

Camunda Exporter (Write) and other components (that read), like Operate, Tasklist and REST API support the definition for an index prefix. Right now there is no single configuration even when using the Standalone Camunda application. This will come with 8.8.

A user would need to configure multiple places to get the prefix usage working correctly. We want to use the Helm charts as the abstraction layer where we can combine all the prefixes under one configuration. 

**Desired outcome and acceptance tests:**

As a user I can define one value, like `indexPrefix` and this sets the necessary configurations in all places

 * [Tasklist](https://docs.camunda.io/docs/next/self-managed/tasklist-deployment/tasklist-configuration/#settings-to-connect-to-a-secured-elasticsearch-or-opensearch-instance)
 * [Operate](https://docs.camunda.io/docs/next/self-managed/operate-deployment/operate-configuration/#elasticsearch-or-opensearch)
 * [ES Exporter](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/exporters/elasticsearch-exporter/?configuration=index#configuration)
 * [Optimize](https://docs.camunda.io/optimize/next/self-managed/optimize-deployment/configuration/shared-elasticsearch-cluster/)
 * [Camunda Exporter
](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/exporters/camunda-exporter/) * REST API

AT:
 
* Using the prefix stores the data in indices that contain the prefix in their name. Data is retrievable by the Webapps without issues.

Relates to https://github.com/camunda/camunda/issues/23807

**Comment by ChrisKujawa** [comment]
@mschoe I think this is something we should also as part of our SM QA:

> Using the prefix stores the data in indices that contain the prefix in their name. Data is retrievable by the Webapps without issues.

**Comment by aabouzaid** [comment]
@ChrisKujawa, to start, I've added the prefix as we discussed. So, it will be part of 8.7 Alpha 2.
If extra work is needed, we can do it in alpha 3.

**Comment by ChrisKujawa** [comment]
For reference https://github.com/camunda/camunda-platform-helm/pull/2643

**Comment by aabouzaid** [comment]
> For reference #2643

Fixed :heavy_check_mark:

**Comment by aabouzaid** [comment]
I'm closing this as it's done in alpha 2, and we could open it again if we needed any changes in alpha 3.
