### ISSUE TITLE
[ISSUE] 8.3.22 has an no charts/identity/charts folder

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#2672]
**Describe the issue:**

Run 
```
helm pull camunda/camunda-platform --version 8.3.22
tar -xzvf camunda-platform-8.3.22.tgz
cd camunda-platform
```

And look into charts/identity/

```
> ls charts/identity 
Chart.yaml  README.md  templates
```

This caused problems in the post-release github actions here:
https://github.com/camunda/camunda-platform-helm/actions/runs/12265296120/job/34221128045

**Actual behavior:**

**Expected behavior:**

**How to reproduce:**

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:

**Comment by hamza-m-masood** [comment]
@jessesimpson36 It seems like this issue has been fixed in the previous release?
Could you please add more information on this issue?

Is it true that there was a glitch on one of the steps and you just had to rebuild it?

**Comment by hamza-m-masood** [comment]
I will close this issue for now. Please reopen if you think this issue still persists.
