### ISSUE TITLE
[ISSUE] Helm Chart Installation Errors with SNAPSHOTS & Alpha Branch

### ISSUE THREAD

**Issue by slolatte** [camunda/camunda-platform-helm#2677]
**Describe the issue:**

 Each of the nightly test runs of the [cross-component test suite](https://github.com/camunda/c8-cross-component-e2e-tests) failed last night due to helm chart installation errors. 

**Actual behavior:**

Failed test runs can be seen here:

[Test Run 1](https://github.com/camunda/c8-cross-component-e2e-tests/actions/runs/12288666994/job/34292886788)
[Test Run 2](https://github.com/camunda/c8-cross-component-e2e-tests/actions/runs/12287074222)
[Test Run 3](https://github.com/camunda/c8-cross-component-e2e-tests/actions/runs/12285656391)

**Expected behavior:**

The helm chart installation should be successful.

**How to reproduce:**

Using the workflows of the test runs linked above. 

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:

**Comment by drodriguez-305** [comment]
When investigating the issue I didn't find any logs that jumped up at me. I ran the test later int he day and the installation of the helm charts were completed. 

Today @slolatte confirmed the nightly test ran without any helm installation errors. Will close this out.
