### ISSUE TITLE
Helm install camunda 8 with keycloak CrashLoopBackOff error

### ISSUE THREAD

**Issue by simonqiang** [camunda/camunda-platform-helm#282]
I have error message from keycloak pod  when try run helm to install camunda 8 from the helm chart. 

below is some of the print out from the pods detail. do you have any advice what is issue ? 

helm install 

kubectl get pods command result 

NAME                                                          READY   STATUS                    RESTARTS           AGE
camunda8-keycloak-0                                   0/1     CrashLoopBackOff   6 (3m52s ago)   27m

kubect describe pods command result. 

Events:
  Type       Reason          Age                        From                        Message
  Warning  Unhealthy  19m (x53 over 28m)    kubelet            Readiness probe failed: Get "http://10.1.0.19:8080/auth/realms/master": dial tcp 10.1.0.19:8080: connect: connection refused
  Warning  BackOff    4m15s (x40 over 24m)  kubelet            Back-off restarting failed container

I am follow below article and using Mac Docker Desktop Kubenetes. 
https://docs.camunda.io/docs/self-managed/platform-deployment/kubernetes-helm/#installing-the-camunda-helm-chart-locally-using-kind

**Comment by Zelldon** [comment]
Hey @simonqiang could you please share the values file you're using? Does this issue persist or did it resolve after some crashes ? Because it might be expected since keycloak depends on PostgreSQL which needs to start first.

**Comment by simonqiang** [comment]
hey @Zelldon, indeed you are right. for the some reason the PostgreSQL is not yet started. not enough cpu core to up all the pods. thanks for the reply.

**Comment by Zelldon** [comment]
Thanks for the response so I will close this. Feel free to reopen if you still see issues
