### ISSUE TITLE
Add Integration test for Optimize

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-helm#283]
Add integration test for Optimize sub chart. In this test, we should try whether the login via keycloak works as expected. See similar tests of operate or tasklist.

Ideally, we check whether there is a REST API for optimize which we can also request and verify whether data was exported.

related to #126

**Comment by Zelldon** [comment]
I guess I still don't know how to add such task to the board @npepinpe am I expected to do this manually?

**Comment by npepinpe** [comment]
If you assign yourself to it, it will show up in the DPT Weekly view. But it seems you already added this to the board :thinking:

**Comment by Zelldon** [comment]
I guess I'm confused

**Comment by Zelldon** [comment]
Done via https://github.com/camunda/camunda-platform-helm/pull/297 login only for now. I saw no way to realize that importing works.
