### ISSUE TITLE
Auto-generate Readme sections from values file

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-helm#293]
There exist certain solutions to autogenerate the readme from the values file for example:

 * https://github.com/bitnami-labs/readme-generator-for-helm
 * https://medium.com/rapids-ai/introducing-frigate-a-documentation-generation-tool-for-kubernetes-1791854031a1

Maybe there's more. Might be worth investigating this so we don't need to do it always by hand which is error-prone and ridiculous.

**Comment by Zelldon** [comment]
> It seems to be possible via [helm-docs](https://github.com/norwoodj/helm-docs) to autogenerate helm documentation
> 
> See https://blog.ediri.io/auto-docs-test-and-release-a-helm-chart-with-github-actions

**Comment by aabouzaid** [comment]
This task has been done, we are using now [readme-generator-for-helm](https://github.com/camunda/camunda-platform-helm/blob/ac7acd916bcc9ca83b19a199154499bec6ae4c45/.github/workflows/chart-update-readme.yaml#L1).
