### ISSUE TITLE
Missing dependency if identity is disabled

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-helm#295]
If we disable identity the installation will fail because Tasklist and Optimize will reference bitnami commons, which is no longer available. To avoid this we should reference the bitnami commons in the parent and make a note in the Notes regarding disabling identity. See related comment here https://github.com/camunda/camunda-platform-helm/pull/291#issuecomment-1109507193

**Comment by Zelldon** [comment]
Ok I added the dependency but I anyway fails to install the chart, because tasklist and others use templates which are defined in identity

```
$ helm install --dry-run test charts/camunda-platform/ --set identity.enabled=false
Error: INSTALLATION FAILED: template: camunda-platform/charts/tasklist/templates/deployment.yaml:51:25: executing "camunda-platform/charts/tasklist/templates/deployment.yaml" at <include "identity.secretNameTasklistIdentity" .>: error calling include: template: no template "identity.secretNameTasklistIdentity" associated with template "gotpl"
```

So I guess it will not bring much benefit for now to add this dependency, so I leave this for now @npepinpe

**Comment by npepinpe** [comment]
Sorry, maybe I misunderstood, but does this mean if I disable Identity, I cannot install Tasklist, Operate, and Optimize?

**Comment by Zelldon** [comment]
Not 100% you can install it if you disable the integration `global.identity.auth.enabled`

**Comment by aabouzaid** [comment]
This issue has been fixed when we introduced [Multi-namespace deployment](https://docs.camunda.io/docs/self-managed/platform-deployment/helm-kubernetes/guides/multi-namespace-deployment/).
