### ISSUE TITLE
Allow to configure imagePullSecrets separately for subcharts

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-helm#302]
Related to https://github.com/camunda/camunda-platform-helm/issues/260#issue-1189472614 

> Hi
> 
> If possible and time permits please add configurable podAnnotations, imagePullSecrets and affinity to charts/operate/deployment.yaml.
> Also if you could make the config volume defaultMode configurable for the charts/zeebe/statefulset.yaml it would safe me from changing this chart before using it.
> 
> Thanks, Friedrich

We should allow configuring the pull secrets for each chart separately. Currently, this is only global possible.

**Comment by fvogl** [comment]
Hi @Zelldon, the global image pull secrets would do, but in the operate deployment yaml there is no imagePullSecrets key at all.

**Comment by Zelldon** [comment]
Ah good point @fvogl :+1:
