### ISSUE TITLE
keycloak pod start error

### ISSUE THREAD

**Issue by zsolimelo** [camunda/camunda-platform-helm#304]
I'm trying Install with  helmchart from https://helm.camunda.io/.
I got this error on keycloak pod log: java.lang.ClassCastException: class [I cannot be cast to class java.util.Map ([I and java.util.Map are in module java.base of loader 'bootstrap')

The full log is attached.
What could be the problem?

Thanks

**Comment by zsolimelo** [comment]
[zeebe_keycloak.txt](https://github.com/camunda/camunda-platform-helm/files/8583001/zeebe_keycloak.txt)

**Comment by Zelldon** [comment]
Hey @zsolimelo did you use a different keycloak version? How does you values files look like if you use any?

**Comment by zsolimelo** [comment]
In the kubernetes node there is running an keycloak in an other namespace, it can be problem?

[values.txt](https://github.com/camunda/camunda-platform-helm/files/8584619/values.txt)

**Comment by Zelldon** [comment]
Looks like this https://github.com/keycloak/keycloak-containers/issues/377#issuecomment-1090104001 but not 100% sure, unfortunately I can't help much here.
