### ISSUE TITLE
Enable operate include fails common.names.dependency.fullname

### ISSUE THREAD

**Issue by margic** [camunda/camunda-platform-helm#319]
I am creating a chart that has a dependency on camunda chart for a dev environment experiment. When enabling operate I get the following error

Error: INSTALLATION FAILED: template: StreamProcessingWorkflow/charts/camunda/charts/operate/templates/deployment.yaml:35:30: executing "StreamProcessingWorkflow/charts/camunda/charts/operate/templates/deployment.yaml" at <include "common.names.dependency.fullname" (dict "chartName" "keycloak" "chartValues" . "context" $)>: error calling include: template: no template "common.names.dependency.fullname" associated with template "gotpl"

This was reported previously in #253 I have identity disabled so the workaround does not work.

**Comment by Zelldon** [comment]
If you have identity disabled please make sure to also disable the identity authentication, via `--set global.identity.auth.enabled=false`

**Comment by margic** [comment]
I have the values as:

`  identity:
    enabled: false
    auth:
      # Disable the Identity authentication for local development
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false`

So that should be good I thought.

**Comment by margic** [comment]
So the answer to my own problem is the identity disable has to be at global scope that was the hint. 
I was creating a nested chart camunda values nested. This doesn't work Identity has to be disabled under global helm values.

<pre>
global:
  identity:
    enabled: false
    auth:
      # Disable the Identity authentication for local development
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false
</pre>
