### ISSUE TITLE
Add podAnnotations and affinity settings for Identity

### ISSUE THREAD

**Issue by McAlm** [camunda/camunda-platform-helm#323]
With reference to #303 these settings are still missing for Identity (and Keycloak).

Would be nice if the values.yaml also forwards these settings to the imported bitnami keycloak chart so that both charts can be deployed on the same node pool.

Thanks! 
McAlm

**Comment by Zelldon** [comment]
Pod annotations for identity added via #327

**Comment by Zelldon** [comment]
Done via https://github.com/camunda/camunda-platform-helm/releases/tag/camunda-platform-8.0.11
