### ISSUE TITLE
Support older Ingress API version

### ISSUE THREAD

**Issue by falko** [camunda/camunda-platform-helm#324]
Make it configurable to generate Ingress configurations using: `apiVersion: extensions/v1beta1` to run on older K8s versions

**Comment by Zelldon** [comment]
I guess it would make more sense to add some conditions to the ingress resources 
https://renehernandez.io/snippets/customize-api-version-helm-templates/

Like:

```
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
```

**Comment by menski** [comment]
@falko any insides what the impact of this is? Is this still relevant? Which customers are using which older k8s versions?

**Comment by aabouzaid** [comment]
We will not make that change since it doesn't have a clear impact and, at the same time, will increase the complexity of the Helm chart.
