### ISSUE TITLE
Camunda Modeler deploy a diagram to zeebe cluster via API

### ISSUE THREAD

**Issue by thanhtuan** [camunda/camunda-platform-helm#328]
Hi everyone,
I'm using camunda-platform 8 running with kind.
I have a problem when trying to deploy the diagram to zeebe via API.
Using TCP is working but I want to use API.
Can you please tell me in this case how can I deploy through the API?
Thank you!

**Comment by Zelldon** [comment]
Hey @thanhtuan could you please elaborate on that? What do you mean via API? How does it differ to `Using TCP is working but I want to use API.`. I'm not sure whether I understand this.

**Comment by thanhtuan** [comment]
> 

Sorry, my bad @Zelldon 
When I expose the TCP port 26500 of the service gateway, I can use modeler deploy to the zeebe cluster.
The question is can I use modeler deploy to the zeebe cluster with API? (use HTTP instead of using TCP port)
I can't find an API for this.
These are the ports in my services:
Gateway:
 `  - port: 9600
      protocol: TCP
      name: http
    - port: 26500
      protocol: TCP
      name: gateway
    - port: 26502
      protocol: TCP
      name: internal`
Zeebe:
`    - port: 9600
      protocol: TCP
      name: http
    - port: 26502
      protocol: TCP
      name: internal
    - port: 26501
      protocol: TCP
      name: command`

**Comment by aabouzaid** [comment]
@thanhtuan Please have a look at the [Zeebe Ingress (gRPC) troubleshooting](https://docs.camunda.io/docs/self-managed/platform-deployment/troubleshooting/#zeebe-ingress-grpc) section where you need to setup TLS to use Zeebe over the Ingress.
