### ISSUE TITLE
Supporting k8s version

### ISSUE THREAD

**Issue by adamvarsanosoluto** [camunda/camunda-platform-helm#329]
Hi,

According to your docs, the Camunda helm chart is supporting the following k8s version:

> Kubernetes >= 1.20+

Does it mean it supports all k8s version that is bigger than 1.20, including 1.20, or does it not include 1.20?

Thanks

**Comment by Zelldon** [comment]
It includes 1.20. Did you encountered any issues?

**Comment by adamvarsanosoluto** [comment]
No, I wasn't sure by the documentation, just want to validate.
Thanks
