### ISSUE TITLE
Scaling Zeebe

### ISSUE THREAD

**Issue by michelefa1988** [camunda/camunda-platform-helm#332]
I have been testing zeebe and trying to analyse how it scales up (and maybe down).

I have started with a configuration below
```
clusterSize: "3"
partitionCount: 3
replicationFactor: "3"
```

With the above configuration, the cluster bootstraps ok. However when I scale up (even updating just the `clusterSize` to 4) a new pod is created the liveliness probe is ok but the readiness probe never returns success. 

The log from the new node is below

```
rg.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] - Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-06-15 16:09:32.549 [] [http-nio-0.0.0.0-9600-exec-1] INFO
org.springframework.web.servlet.DispatcherServlet - Initializing Servlet 'dispatcherServlet'
2022-06-15 16:09:32.553 [] [http-nio-0.0.0.0-9600-exec-1] INFO
org.springframework.web.servlet.DispatcherServlet - Completed initialization in 4 ms
2022-06-15 16:10:22.990 [] [atomix-cluster-events] ERROR
io.camunda.zeebe.broker.clustering - Static configuration of node 2 differs from local node 3: NodeId: 0 <= 2 < 4, ClusterSize: 3 == 4, PartitionsCount: 3 == 3, ReplicationFactor: 3 == 3.
2022-06-15 16:10:26.039 [] [atomix-cluster-events] ERROR
io.camunda.zeebe.broker.clustering - Static configuration of node 0 differs from local node 3: NodeId: 0 <= 0 < 4, ClusterSize: 3 == 4, PartitionsCount: 3 == 3, ReplicationFactor: 3 == 3.
2022-06-15 16:10:26.937 [] [atomix-cluster-events] ERROR
io.camunda.zeebe.broker.clustering - Static configuration of node 2 differs from local node 3: NodeId: 0 <= 2 < 4, ClusterSize: 3 == 4, PartitionsCount: 3 == 3, ReplicationFactor: 3 == 3.
2022-06-15 16:10:34.811 [] [atomix-cluster-events] ERROR
io.camunda.zeebe.broker.clustering - Static configuration of node 2 differs from local node 3: NodeId: 0 <= 2 < 4, ClusterSize: 3 == 4, PartitionsCount: 3 == 3, ReplicationFactor: 3 == 3.
```

Any ideas about why it happens? Will it be possible to scale Zeebe or must we destroy the cluster and recreate? I was unable to find much documentation on this so any help will be appreciated.

**Comment by Zelldon** [comment]
Hey @michelefa1988 sorry to tell you that but currently zeebe is not able to dynamically scale, even if this might be naturally in the Kubernetes environment. Zeebe is a bit more complex than just a normal stateless app deployment. Based on the architecture it is not that easy to implement see further details in this issue here https://github.com/camunda/zeebe/issues/4391

Since this is a Zeebe related issue I will close this one. Feel free to add a comment to the linked issue above.

**Comment by michelefa1988** [comment]
@Zelldon Good to know. Its pretty strange the docs do not mention anything, its actually on the contrary,  my understanding is how fault tolerant/ scalable it is :)

Thanks for your reply though
