### ISSUE TITLE
Connect to external elastic search

### ISSUE THREAD

**Issue by adamvarsanosoluto** [camunda/camunda-platform-helm#333]
Hi,
I think this is better to use manage service as a database and not manage the database myself.
So I want to connect to an external Elastic Search.

According do [Camunda Helm Chart's values.yaml](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml), I can see that I can config only host and port.
Where can I put the token?

Elastic search is secured by token, usually passed in the header.
I'm using Elastic Search of [Logz.io](https://docs.logz.io/api/#section/Authentication)

Thanks

**Comment by Zelldon** [comment]
As far as I know this is not yet supported by the different components zeebe/operate. But maybe I'm wrong. @npepinpe do you know any specific here?

**Comment by adamvarsanosoluto** [comment]
Do You mean there is no option to connect Camunda to external Elastic Search?
In case there is no such option, is it in the roadmap?

**Comment by npepinpe** [comment]
You can connect to an external Elasticsearch instance, however, the only authentication option the exporter supports is basic auth. I'm not aware of any short- or mid-term plans to implement anything else, but I do know it's been requested before (notably connecting to an AWS OpenSearch instance), so I'm sure it will be there eventually. In the meantime, the only thing you could do as a workaround is add a proxy in between which authenticates your requests with the token, but I understand that's less than ideal.

**Comment by adamvarsanosoluto** [comment]
OK, I want to use Elasticsearch basic auth:
For example: 
`curl http://127.0.0.1:9200 -u [username]:[password]`

Where in the[ values.yaml](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml) I can set the credentials? 
I can see only the host, port or URL

Thanks

**Comment by Zelldon** [comment]
Please take a look at the docs https://docs.camunda.io/docs/self-managed/operate-deployment/configuration/#elasticsearch here you can find several properties which you can set. For example `camunda.operate.zeebeElasticsearch.username` would be as environment variable: `CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_USERNAME`  which you can set under [`operate.env`](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml#L427)
