### ISSUE TITLE
 Run Integration against newest kubernetes cluster version

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-helm#336]
We currently support multiple versions 1.20+, our gke cluster currently runs on 1.21. If we want to support multiple versions I think we should at least test always against the latest and against the lowest we support. 

We can set up a new cluster, which will be automatically updated and is only for our integration tests. This allows finding issues with Kubernetes versions ( especially API issues) early. 

Related https://github.com/camunda/camunda-platform-helm/issues/324

**Comment by aabouzaid** [comment]
I'm closing this issue since we have an epic for that topic in the distro repo.
