### ISSUE TITLE
How to disable `podAntiAffinity` defaults?

### ISSUE THREAD

**Issue by upgradingdave** [camunda/camunda-platform-helm#338]
While doing performance testing it would be interesting to schedule multiple zeebe broker pods onto a single GKE node. For example, we have GKE nodes with 15.89 allocatable vCPUs and would like to schedule 3 broker pods (each using 5 vCPUs) on each node. 

We tried disabling the `podAntiAffinity` as shown below but GKE is still scheduling one broker pod per GKE node? Any ideas on how to disable the `podAntiAffinity`?

```
zeebe:
  affinity:
    podAntiAffinity: {}
```

**Comment by Zelldon** [comment]
Hey @upgradingdave thanks for reporting! I would expect that this works, could you try to set `zeebe.affinity={}` or generate the templates via `helm template <release-name> camunda/camunda-platform -f values.yaml` and attach the output here, so I can take a look?

**Comment by upgradingdave** [comment]
Thanks for the tip to use `helm template` command, @Zelldon!

The default podAntiAffinity rules still appear in the output from `helm template` when I use this: 

```
zeebe:
  affinity: {}
```

However, when I use `null`, I don't see podAntiAffinity in the `helm template` output, so I think this might work: 

```
zeebe:
  affinity: null
```

I think this should work. We're about to test in our environment and I'll follow up to confirm in a few minutes.

Thanks again!

**Comment by upgradingdave** [comment]
We confirmed that `affinity: null` does indeed allow multiple pods to be scheduled on the same node. Thanks again for your help!

**Comment by Zelldon** [comment]
Thats great! Thanks for coming back and closing the issue :+1:
