### ISSUE TITLE
Elasticsearch 7.17.3 download failed in Kubernetes pod rolled out from helm.camunda.io

### ISSUE THREAD

**Issue by tokarenko** [camunda/camunda-platform-helm#339]
Steps to reproduce:

$ helm repo add camunda https://helm.camunda.io
$ helm repo update
$ wget https://raw.githubusercontent.com/camunda/camunda-platform-helm/main/kind/camunda-platform-core-kind-values.yaml
$ helm install camunda-platform camunda/camunda-platform -f camunda-platform-core-kind-values.yaml
$ kubectl get pods
NAME                                   READY   STATUS                        RESTARTS        AGE
...
elasticsearch-master-0         0/1          Init:ImagePullBackOff   0                         33m

$ kubectl get events
Failed to pull image "docker.elastic.co/elasticsearch/elasticsearch:7.17.3": rpc error: code = Unknown desc = failed to pull and unpack image "docker.elastic.co/elasticsearch/elasticsearch:7.17.3": failed to copy: httpReadSeeker: failed open: unexpected status code https://docker.elastic.co/v2/elasticsearch/elasticsearch/blobs/sha256:3c91aa69ae062dd312fbe54fa0d3e8e306e506f4e9bfbad702ae8ebc499fe7f2: 403 Forbidden

$ wget https://docker.elastic.co/v2/elasticsearch/elasticsearch/blobs/sha256:3c91aa69ae062dd312fbe54fa0d3e8e306e506f4e9bfbad702ae8ebc499fe7f2
--2022-07-06 14:14:35-- https://docker.elastic.co/v2/elasticsearch/elasticsearch/blobs/sha256:3c91aa69ae062dd312fbe54fa0d3e8e306e506f4e9bfbad702ae8ebc499fe7f2
Resolving docker.elastic.co (docker.elastic.co)... 34.68.230.202
Connecting to docker.elastic.co (docker.elastic.co)|34.68.230.202|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.

Subitted issue to Elasticsearch support https://github.com/elastic/elasticsearch/issues/88306

**Comment by RViththakan** [comment]
How did you resolved it?

**Comment by tokarenko** [comment]
@RViththakan , I performed installation through VPN connection

**Comment by RViththakan** [comment]
I have few questions
You have used this command below to install the Camunda kind version

`helm install camunda-platform camunda/camunda-platform -f camunda-platform-core-kind-values.yaml`

It is mainly used for the development purpose only right?
I followed the same steps and I got a Chart.yaml missing error.

After that I followed the normal installation using helm 3 and helm 2 using the below commands

```
helm install --name camunda ./camunda-platform/
helm3 install camunda ./camunda-platform/
```

I received the below error.
`
Error: INTALLATION FAILED: template: camunda-platform/charts/optimize/templates/deployement.yaml:47:22: executing "camunda-platform/charts/optimize/templates/deployment.yaml" at <include "camundaPlatfrom.issuerBackendUrl" .>: error calling include: template: camunda-platform/templates/_helpers.tpl:63:10: executing "camundaPlatform.issuerBackendUrl" at <include "common.names.dependency.fullname"> (dict "chartName" "keycloak" "chartValues" . "context" $)>: error calling include template no template "common.names.dependency.fullname" associated with template "gotpl"`

Can you help me with this?

**Comment by tokarenko** [comment]
Please find below my notes on installation commands for Ubuntu. I hope you will find the answer to your question.
Regarding the production/development usage of camunda/camunda-platform. My understanding is that in order to use it in production you should buy a license for parts that are not open source (see https://camunda.com/blog/2022/05/how-open-is-camunda-platform-8/)

```
#Install Docker
sudo su
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
apt-get update
apt-get install docker-ce docker-ce-cli containerd.io docker-compose docker-compose-plugin
usermod -aG docker $USER
exit
#logout/login to apply change in group membership
#test
docker run hello-world

#Choose either of two options below

#OPTION 1. Install Camunda in Docker: https://github.com/camunda/camunda-platform#using-docker-compose
    git clone https://github.com/camunda/camunda-platform
    docker-compose up -d

#OPTION 2. Install Camunda in KIND
    sudo su
    #Install Kubernetes
    curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/google.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/google.gpg] http://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list > /dev/null
    apt-get update
    apt-get install kubectl

    #Install helm
    snap install helm --classic

    #Install KIND
    curl -L "https://kind.sigs.k8s.io/dl/v0.14.0/kind-$(uname)-amd64" -o /usr/local/bin/kind
    chmod +x /usr/local/bin/kind

    exit
    #test
    kubectl version --client
    kind

    #Install Camunda
    kind create cluster
    helm repo add camunda.io https://helm.camunda.io
    helm repo add camunda.cloud https://helm.camunda.cloud
    helm repo update
    wget https://raw.githubusercontent.com/camunda/camunda-platform-helm/main/kind/camunda-platform-core-kind-values.yaml
    helm install camunda-platform camunda/camunda-platform -f camunda-platform-core-kind-values.yaml
    #Tear down:
    helm uninstall camunda-platform
    kind delete cluster
```

**Comment by RViththakan** [comment]
Thanks for the info !!
I have few more questions as well. 
As per the official documentation 
`https://docs.camunda.io/docs/self-managed/platform-deployment/kubernetes-helm/ `
Kind is only for development purpose only right?
Here KIND installation is done with the following command 
  ```
#Install KIND
    curl -L "https://kind.sigs.k8s.io/dl/v0.14.0/kind-$(uname)-amd64" -o /usr/local/bin/kind
    chmod +x /usr/local/bin/kind
```

1. What is KIND? and Is it safe in Production?

2. When comparing with the official documentation you have added Installation of KIND cluster, So for deploying Camunda in the the Kubernetes cluster do I need further steps to be done rather than what is mentioned in the documentation? `https://docs.camunda.io/docs/self-managed/platform-deployment/kubernetes-helm/  `
Deploying in the Cluster mean How to deploy the chart.yaml, values.yaml and dependencies (Sub-Charts) found within camund-platform folder.

3. Following the helm installation I got an error 
`Error: INSTALLATION FAILED: Kubernetes cluster unreachable: Get "https://localhost:8080/version": context deadline exceeded`
are you aware of this?

**Comment by tokarenko** [comment]
I didn’t plan for production. I tried two options recommended for development: 1. Docker containers and 2. Kubernetes in Docker (KIND). Of these two only pure Docker images operated as expected. KIND failed to bring up servers. So, I settled on pure Docker containers. For production they recommend Kubernetes cluster (not in Docker - KIND). I remember that Docker images may be used as well. Regarding the error you get. It seems that you do not have Kubernetes cluster operational. The command “kind create cluster” should bring it up.

**Comment by RViththakan** [comment]
Ok Thank you !
Do you have any idea on how to use it for production purpose?

**Comment by tokarenko** [comment]
Look no further than official guide at https://docs.camunda.io/docs/self-managed/platform-deployment/
```
You have the following options to run the above components in a self-managed fashion:
- Kubernetes: We strongly recommend using Kubernetes to run Camunda Platform 8 in production.
- Docker: You can run the provided Docker images of the components, also in production.
```

**Comment by npepinpe** [comment]
Alternatively, you can supply your own Elasticsearch image, by overwriting the image configuration of the Elastic chart to, say, use the default Docker hub.

```yaml
elasticsearch:
  enabled: true
  image: "elasticsearch"
  imageTag: "7.17.3"
```

If you had a different default registry configured, you could replace the image value with `image: "docker.io/library/elasticsearch"`.

**Comment by tokarenko** [comment]
Thank you Nicolas for pointing to this option! This is much better.

**Comment by npepinpe** [comment]
Note that Elastic recommends using the image from their own Docker registry for production use cases. I'm not sure what the differences are (since both are maintained by Elastic), but it might be sufficient for your use case. Another option is to get the image from their own registry and push it somewhere accessible for you, e.g. your cloud provider's registry.
