### ISSUE TITLE
Add resources option to curator cronjob

### ISSUE THREAD

**Issue by m-myska** [camunda/camunda-platform-helm#354]
Resource quotas enforces to run jobs with specified cpu/memory request and limit.
Proposed solution to add into curator-cronjob:
```
{{- if .Values.retentionPolicy.resources }}
resources:
  {{ .Values.retentionPolicy.resources | nindent 16 }}
{{- end }}
```

**Comment by npepinpe** [comment]
Good point, the curator job in general could use some more configuration options.

**Comment by drodriguez-305** [comment]
After further review we still have this for older versions of the helm charts 8.1 and 8.2. Adding this feat to those versions.

**Comment by drodriguez-305** [comment]
Confirmed with the team since 8.1 is EOL we will only add this to 8.2.
