### ISSUE TITLE
Cannot deploy helm chart with persistent volumes type Local

### ISSUE THREAD

**Issue by CanadianHorseman** [camunda/camunda-platform-helm#355]
Hello
I'm trying to deploy Camunda Platform 8 on-premises.
I've got k8s baremetal cluster consisting of two nodes.
I've made changes (replicas count and so on) in values.yaml.
I've created several PV on both nodes of type Local Persistent Volume.
All PVC seems to be Bound but some pods (elastic and zeebe itself) are failing to schedule and stuck in Pending state.
Here is why: 0/2 nodes are available: 2 node(s) had volume node affinity conflict.
But I can't understand why and what can I do.

Any help would be appreciated. 

![image](https://user-images.githubusercontent.com/3437226/179617679-dadce019-7cb1-40b9-832e-998e9fbd2e7f.png)

**Comment by RViththakan** [comment]
Hello there !
I have few questions regarding the deployment.
When I tried to install camunda using the below command
`helm install <RELEASE NAME> camunda/camunda-platform`
I couldn't able to install it.

I tried two ways
First step is to install using the below command
`helm install <RELEASE NAME> camunda/camunda-platform `
Second step is downloading the camunda depository and installing using
`helm install camunda ./camunda-platform/`

In both of these instances I'm constantly getting error and the deployment is not done. Can you please let me know the steps you followed?

**Comment by npepinpe** [comment]
You should definitely install always using `helm install <RELEASE NAME> camunda/camunda-platform` unless you want to test out a development version.

The error you report relating to the volumes seems to indicate something about volume affinity. Volume affinity has to do with volumes being mounted to specific nodes. That's not something configured by this chart, but instead something to do with your k8s installation. [See the official docs about this](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#node-affinity). There's plenty of Stackoverflow posts which can help you troubleshoot your local k8s installation, probably better than I can.

**Comment by RViththakan** [comment]
yh It is resolved
