### ISSUE TITLE
Cannot deploy helm chart with persistent volumes in NFS server

### ISSUE THREAD

**Issue by RViththakan** [camunda/camunda-platform-helm#356]
The persistence volume is configured in the separate NFS server. But when deploying the Camunda using the helm charts, zeebe (3), Elasticsearch (2) and postgresql (1) is showing the persistence volume claim error. Does anyone have any idea from where postgresql is deployed here? I couldn't able to find it in the values.yaml and Chart.yaml and not within sub-charts also. All together 6 pods are in pending stage because of the persistence volume error. Anyone know how to resolve the persistence volume claim error in camunda?

**Comment by npepinpe** [comment]
Postgresql is a dependency of the Keycloak chart, itself a dependency of the Camunda Identity chart.

You configure it as such:

```yaml
identity:
  keycloak:
    postgresql:
      # postgresql values here
```

[You can find the Postgresql values here](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)

**Comment by RViththakan** [comment]
Thanks. It is resolved
