### ISSUE TITLE
Specify a default non-root user for our own charts

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda-platform-helm#368]
**Description**

We currently specify no default security context (neither pod nor container level) for our own charts. One of the downside is that if users forget to configure it, their containers may run with unexpected privileges, something which can become a security issue.

It's common to configure a default non-root user to mitigate these issues for users deploying their charts on permissive platforms.

NOTE: this may cause issues with the following bug (https://github.com/helm/helm/issues/9136) and we would have to update the OpenShift profile after, but it _is_ safer for users in the end.

**Comment by menski** [comment]
We will wait for Helm fix, and not invest into solving this on our side.

**Comment by aabouzaid** [comment]
Fixed by #864
