### ISSUE TITLE
Simplify the getting started experience

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda-platform-helm#369]
**Description**

I've noticed many new issues aren't problems with the chart itself, but rather problem installing them to the user's custom Kubernetes installation.

One main area is for users who just want to test it out, i.e. the trial or out of the box experience. For example, sometimes there is no storage class defined on their cluster. Sometimes they have questions about the charts we depend on (e.g. Keycloak, Postgresql) and how to configure these. Or they have the same bug that comes up (e.g. set `identity.enabled` to false but forget to set `global.identity.auth.enabled` to false as well).

I think it would be great if we had a getting started guide that focuses on the initial, first-time experience, something which help users ensure their environment is ready (e.g. Kubernetes version, storage class capabilities, tooling version), which application to configure and why, how to configure dependency charts, and a troubleshooting section for common installation errors which are more likely to pop up on your first run. 

### Related tickets
* [SUPPORT-18598](https://jira.camunda.com/browse/SUPPORT-18598) [not as a direct issue, but underlined the importance of it]

**Comment by aabouzaid** [comment]
In camunda/camunda-platform-docs/pull/1241 I've introduced a new structure in our docs which will make it easy to add guides for different use cases.

**Comment by menski** [comment]
We will revisited this after we added support for Azure and Google to have the full picture and do a decision how to structure the content better.

**Comment by aabouzaid** [comment]
We have more evidence that such a guide is essential to help new users use Camunda 8 easily.

I will link the distro issue with all support links.
