### ISSUE TITLE
Move the charts on Artifact Hub to Camunda org

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#371]
Currently, Camunda Platform Helm charts on [Artifact Hub](https://artifacthub.io/packages/helm/camunda-platform/camunda-platform) are under @Zelldon user.

For better structure, we need to move the charts on Artifact Hub to Camunda org/repo.

We need to do the following:
- [x] Create `camunda` org (it was already created for Camunda Platform v7 chart).
- [x] Invite @Zelldon to the Camunda org.
- [x] Transfer `camunda-platform` to Camunda org.
- [x] We could also move from AH repo `camunda-platform` to `camunda`.

And to avoid confusion, we also need to do some changes in the [camunda-community-hub/camunda-helm](https://github.com/camunda-community-hub/camunda-helm):
- [x] Rename the `camunda` repo to `camunda-community-hub`.
- [x] Rename the community hub sub domain `helm.camunda.cloud` to `helm.cch.camunda.cloud`.

Nice to have:
- [x] Add the [Official Badge](https://artifacthub.io/docs/topics/repositories/#official-status) to our Helm chart page in Artifact Hub (Artifact Hub issue no. [#2182](https://github.com/artifacthub/hub/issues/2182)).

**Comment by Zelldon** [comment]
> We could also rename the repo to camunda.

Which repo you want to rename?

**Comment by aabouzaid** [comment]
> > We could also rename the repo to camunda.
> 
> Which repo you want to rename?

This one `camunda-platform`.

The chart URL in AH shows as:
> https://artifacthub.io/packages/helm/[REPO]/[CHART]

So instead of:
> https://artifacthub.io/packages/helm/camunda-platform/camunda-platform

by renaming the repo to `camunda` we will have:
> https://artifacthub.io/packages/helm/camunda/camunda-platform
