### ISSUE TITLE
Keycloak: Failed to connect to database

### ISSUE THREAD

**Issue by schmetzyannick** [camunda/camunda-platform-helm#375]
Hi,
I just wanted to get started with camunda 8 by using this helm chart. Unfotunatly just running:
> helm install camunda camunda/camunda-platform -n camunda

Is not working for me.

It seems like the keycloak service is not able to connect to the pg database. 
Found in the logs from the keycloak pod: 
> 14:39:52,288 FATAL [org.keycloak.services] (ServerService Thread Pool -- 62) Error during startup: java.lang.RuntimeException: Failed to connect to database
> .....
> Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "bn_keycloak"

And in the pg pod log: 
> 2022-08-08 14:39:52.273 GMT [728] DETAIL:  Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
> 2022-08-08 14:42:29.295 GMT [965] FATAL:  password authentication failed for user "bn_keycloak"

**Comment by aabouzaid** [comment]
@schmetzyannick could you please give more details? Like the the environment (e.g. which provider), Kubernetes cluster (which version), and how to reproduce the issue?

Also, is that the first deployment? I remember I saw a similar issue when the PVC is not remove after the first try.
e.g. if you test a different configuration from scratch, you need to delete all Camunda Platform resources including the PVC which are not deleted by default (or simply delete the whole namespace and start over).

**Comment by schmetzyannick** [comment]
PVC was the problem
