### ISSUE TITLE
[ENHANCEMENT] Support startupProbe, readinessProbe, livenessProbe in all charts

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#392]
**Description of the use case:**

Currently we only have `readinessProbe` in some of the Camunda components charts.
Also we don't use `startupProbe` or `livenessProbe` at all. 

**Desired outcome and acceptance tests:**

- Add all the 3 probs to all sub-charts.
- The probs should have a mechanism to enable/disable them.
- By default, only `readinessProbe` should be enabled and the other 2 probs disabled.

**Comment by menski** [comment]
Zeebe: https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/operations/health/
Operate: https://docs.camunda.io/docs/next/self-managed/operate-deployment/operate-configuration/#monitoring-operate
Tasklist: https://docs.camunda.io/docs/next/self-managed/tasklist-deployment/tasklist-configuration/#monitoring-and-health-probes
Identity: https://docs.camunda.io/docs/next/self-managed/identity/deployment/application-monitoring/

**Comment by megglos** [comment]
> The probs should have a mechanism to enable/disable them.

@aabouzaid I actually got confused by a zeebe pod never getting restarted due to the liveness probe being disabled by default :D what was the reasoning behind leaving it disabled by default?

**Comment by aabouzaid** [comment]
@megglos The liveness could be dangerous if the user is unaware of its consequences, especially since the timeout values could vary between environments.

There are a couple of posts explaining what could go wrong with liveness, one of my favorites is [Liveness Probes are Dangerous](https://srcco.de/posts/kubernetes-liveness-probes-are-dangerous.html).

That's why we keep it disabled by default and leave the decision to the user.
