### ISSUE TITLE
[BUG] broken link for zeebe gateway

### ISSUE THREAD

**Issue by nhomble** [camunda/camunda-platform-helm#398]
**Describe the bug:**

404 when visiting the link present in https://github.com/camunda/camunda-platform-helm/tree/main/charts/camunda-platform/charts/zeebe-gateway

[this is the actual link](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/README#zeebe-gateway)

**Comment by aabouzaid** [comment]
@nhomble good catch, thank you :ok_hand: 
Fixed by [830e976](https://github.com/camunda/camunda-platform-helm/commit/830e976c9e2cc19216b6e04da162c23ae38f591d)
