### ISSUE TITLE
[ENHANCEMENT] Generate markdown from values file

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#401]
**Describe the use case:**

As a maintainer, I need an easy way to generate a markdown from the chart values file to update the in-repo docs (the README files).

**Describe the enhancement/feature:**

Currently generating the values in README file are semi-automated using [convertValuesDoc.sh](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/convertValuesDoc.sh) script. The script reduces the time to update in-repo docs, but there are still many copy and paste needed.

And since this is not a unique problem, it has probably been solved before.

**Desired outcome and acceptance tests:**
- Evaluate the available tools and select one (suggestion: Bitnami [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm))
- The tool should be easy to use and doesn't need many manual interactions.

**Comment by jessesimpson36** [comment]
The problem I have with readme-generator-for-helm is that it really bulks up  the space between every config option, adding things like `@param ` everywhere. They expect each set of text to contain one line.  And I really want to reduce the amount of scrolling up-and-down people already have to do in our values.yaml file.

I looked into this one: https://github.com/norwoodj/helm-docs/tree/master ,  which I liked that you could specify a golang template,  but it has a limitation where you can't take subsections of the values and make different sections out of it  the way we do with our README.
