### ISSUE TITLE
Operate and Tasklist should be preconfigured for Identity JWT tokens use

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda-platform-helm#404]
Operate and Tasklist must have two additional parameters configured in order to allow secured access to Public API.

Following parameters must be added: 

Parameter name | Description | Example value
-- | -- | --
spring.security.oauth2.resourceserver.jwt.issueruri | Token issuer URI | http://localhost:18080/auth/realms/camunda-platform
spring.security.oauth2.resourceserver.jwt.jwkseturi | Complete URI to get public keys for JWT validation | http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/certs

When using locally with docker-compose values look like this:
```
- SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=http://localhost:18080/auth/realms/camunda-platform
- SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI=http://keycloak:8080/auth/realms/camunda-platform/protocol/openid-connect/certs
```

Documented here: https://docs.camunda.io/docs/self-managed/operate-deployment/operate-authentication/#identity

**Comment by sdorokhova** [comment]
Probably related support case: https://jira.camunda.com/browse/SUPPORT-14564

**Comment by Zelldon** [comment]
I dont see that as a bug, it is more a missing feature which hasn't implemented yet. When we added identity, operate/tasklist didn't supported that feature. 

Tbh I see that in the teams responsibility to add such things.  

BTW if we add this we can simplify the integration tests, since we do not need to use the cookie approach anymore.

**Comment by ajeans** [comment]
Hello @Zelldon 

Well it was quite painful on our end with a lot of back and forth.

Some of our SUPPORT tickets end up being known gaps between teams / products and it doesn't feel as coherent and polished as it could be as a consumer of the ecosystem.

We are going to try to add the two values manually ahead of the change and see if that make our JWTs "stick".

Thanks!

\cc @piermotte @B-hamza

**Comment by ajeans** [comment]
@sdorokhova we also use Optimize, do you know if it requires the same configuration keys to work?

**Comment by sdorokhova** [comment]
Hello @ajeans ,
I spoke to Optimize devs and yes, you would need additional parameters for Optimize:
```
CAMUNDA_OPTIMIZE_API_JWTSETURL=<same values as for Operate>
CAMUNDA_OPTIMIZE_API_AUDIENCE=optimize-api
```
\cc @grlimacan
