### ISSUE TITLE
[ENHANCEMENT] Update default version to track latest camunda release

### ISSUE THREAD

**Issue by upgradingdave** [camunda/camunda-platform-helm#413]
The default `values.yaml` file currently sets a [default image tag version to 8.0.0](https://github.com/camunda/camunda-platform-helm/blob/8b5aade10604c443b447b516e01bf8494ff086dc/charts/camunda-platform/values.yaml#L37). 

I suggest two possible enhancements: 

1. Can this updated to 8.0.6? Is there any negative effects of doing so?
2. Would it be possible to somehow automatically update this value in this repo each time there's a new release of Camunda?

**Comment by aabouzaid** [comment]
I think it's a good idea to provide a GitHub workflow to update the version of the images when there is a patch release.
I will try to work on this when 8.1.0 is released.

**Comment by falko** [comment]
big +1

**Comment by felix-mueller** [comment]
@aabouzaid lets try to include this during next planning

**Comment by felix-mueller** [comment]
Wow even  better,thank you !
