### ISSUE TITLE
ServiceMonitor name is hard coded and contains ccsm

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-helm#424]
The name of the service monitor is hard coded and contains still ccsm, we should change this (based on the release maybe?) 
https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/templates/service-monitor.yaml#L5

**Comment by aabouzaid** [comment]
Fixed by: [60a47ae](https://github.com/camunda/camunda-platform-helm/commit/60a47aea7ca0e84cae5e4ece0e34a864bd510100)
