### ISSUE TITLE
[ENHANCEMENT] Default keycloak configuration with zeebe-gateway endpoint authentication

### ISSUE THREAD

**Issue by vctrmn** [camunda/camunda-platform-helm#444]
**Describe the use case:**

I would like to deploy BPMN/DMN from Camunda Modeler (OAuth), with the default keycloak configuration. 

**Describe the enhancement/feature:**

Default keycloak configuration with zeebe-gateway endpoint authentication for deployment from camunda modeler.

**Comment by aabouzaid** [comment]
@rob2universe I believe that's related to what you are working on now.
Do you think that we can include that in the default Keycloak config?

**Comment by aabouzaid** [comment]
Zeebe Gateway auth has been enabled by default in Camunda [Helm chart 8.2.3](https://github.com/camunda/camunda-platform-helm/releases/tag/camunda-platform-8.2.3).
