### ISSUE TITLE
ingress.yaml line 23 nil pointer exception .Subcharts.identity.Subcharts.keycloak

### ISSUE THREAD

**Issue by mercury77** [camunda/camunda-platform-helm#447]
**Describe the bug:**
camunda-platform/templates/ingress.yaml:23:63: executing "camunda-platform/templates/ingress.yaml" at <.Subcharts.identity.Subcharts.keycloak>: nil pointer evaluating interface {}.identity

**Comment by aabouzaid** [comment]
@mercury77 Please give more details how you try to install the chart.
If you are installing it from the Git repo (not Helm repo), then you need to add the dependencies too:

```
helm repo add elastic https://helm.elastic.co
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
```

**Comment by mercury77** [comment]
Thank you so much for replying me Ahmed,
I'm using the following ingress,yaml file during the installation of
camunda (taken from official camunda website) :

myingressfile.yaml :

global:
  ingress:
    enabled: true
    className: nginx
    host: "myserver"
  identity:
    auth:
      publicIssuerUrl: "http://myserver/auth/realms/camunda-platform"
      operate:
        redirectUrl: "http://myserver/operate"
      tasklist:
        redirectUrl: "http://myserver/tasklist"
      optimize:
        redirectUrl: "http://myserver/optimize"

identity:
  contextPath: "/identity"
  fullURL: "http://myserver/identity"

operate:
  contextPath: "/operate"

optimize:
  contextPath: "/optimize"

tasklist:
  contextPath: "/tasklist"

zeebe-gateway:
  ingress:
    enabled: true
    className: nginx
    host: "zeebe.myserver"

using :
helm install myrelease camunda/camunda-platform \
--namespace ingress-basic \
-f myingressfile.yaml

it seems that your ingress.yaml chart file is not able to inject the
servicename for each operate identity tasklist etc and installation fails

Il giorno lun 17 ott 2022 alle ore 22:23 Ahmed AbouZaid <
***@***.***> ha scritto:

**Comment by aabouzaid** [comment]
@mercury77 which Helm version do you use?
```
helm version
```

**Comment by mercury77** [comment]
version.BuildInfo{Version:"v3.1.1",
GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean",
GoVersion:"go1.13.8"}
on ubuntu linux (Linux subsystem for window 10)

Il giorno mar 18 ott 2022 alle ore 16:33 Ahmed AbouZaid <
***@***.***> ha scritto:

**Comment by aabouzaid** [comment]
@mercury77 this Helm version is a bit old; please use the latest version or the same version as in [.tool-versions](https://github.com/camunda/camunda-platform-helm/blob/3af6b5a9464309d96c0f3ba8d98501e516e0adf3/.tool-versions#L1) file.

**Comment by mercury77** [comment]
Sorry @aabouzaid I don't think that a more recent version of helm will fix a Service name that is not injected in ingress template file .

.Subcharts.identity.Subcharts.keycloak  this will never be expanded since it does not exists

**Comment by aabouzaid** [comment]
@mercury77 it's available because of the Camunda Platform Helm chart hierarchy.
You can read more about it here: [Dependencies](https://github.com/camunda/camunda-platform-helm/tree/main/charts/camunda-platform#dependencies).

Also, make sure to use the latest version because there was an issue with Keycloak dependency in one of the recent versions.

Before updating, try the following:
```
helm template camunda/camunda-platform --version 8.1.1
```

If it didn't work, then try to update the Helm CLI.

The same structure is already used and working as expected. e.g. "[.Subcharts.identity](https://github.com/camunda/camunda-platform-helm/blob/60a47aea7ca0e84cae5e4ece0e34a864bd510100/charts/camunda-platform/templates/ingress.yaml#L24)".
