### ISSUE TITLE
[ENHANCEMENT] The Keycloak theme is created from Identity image and mounted to Keycloak

### ISSUE THREAD

**Issue by dlavrenuek** [camunda/camunda-platform-helm#448]
**Describe the use case:**

To provide a seamless Camunda experience we provide a Keycloak theme for the login screen. Starting with [Identity 8.1.1](https://github.com/camunda-cloud/identity/releases/tag/8.1.1) / 8.0.8 (yet to be released) this theme is included in the Identity image and should be mounted to the Keycloak container.

**Describe the enhancement/feature:**

With docker compose it is solved by mounting a shared volume to Identity and Keycloak container: https://github.com/camunda-cloud/identity/blob/main/docker-compose.yml#L17

The theme is stored at `/app/keycloak-theme` in the Identity image and should be mounted to `/opt/bitnami/keycloak/themes/identity` in Keycloak container.

**Desired outcome and acceptance tests:**
When Camunda Platform 8 is started using helm charts and a user logs in any of the C8 applications
- [ ]  the login screen contains the Camunda theme instead of Keycloak's default one.

**Comment by aabouzaid** [comment]
For the records, I've tested the output of #487 with @dlavrenuek and it worked as expected.
