### ISSUE TITLE
[BUG]Deploying to EKS, postgres database fails to start

### ISSUE THREAD

**Issue by halestv** [camunda/camunda-platform-helm#450]
I am new to deploying Camunda on Kubernetes. but have created a EKS stack and installed helm . 

When I try and push the charts from helm, all of the services start up , but the postgres db fails almost instantly,  and I cannot get any meaningful logs from the container to determine the problem. 

I am using EFS as storage class, and everything is mounted correctly, and I am not overriding any default values.. strictly fresh out of the box deployment. 

have you come across this problem ?

**Comment by halestv** [comment]
After looking into more, the problem lies with the postgres image set up:
`mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied`

I think it is fixed by passing "--set volumePermissions.enabled=true" when deploying the helm charts, but currently investigating further

**Comment by aabouzaid** [comment]
@halestv is this issue still valid?

If yes, could you please add more details about the setup?
Any special config you have in your EKS, also the version of:
- EKS
- Camunda Chart
- Helm CLI
