### ISSUE TITLE
[BUG] Cannot disable graphql playground in tasklist

### ISSUE THREAD

**Issue by vincentgiraud** [camunda/camunda-platform-helm#453]
**Describe the bug:**

While trying different settings for graphqlPlaygroundEnabled ("", "false", false) or removing env var GRAPHQL_PLAYGROUND_ENABLED, I cannot log in Tasklist with demo/demo

**Actual behavior:**

Cannot log in, UI message "session expired". also the dev inspector is still showing a /graphql request ending in a 403 error (Invalid CORS request)

**Expected behavior:**

Logging in Tasklist with demo/demo. It works with Operate with the same OpenShift route setting.
Not seing a/graphql request after /login

**Environment:**
- Platform:  OpenShift 4
- Chart version:  8.x

**Comment by aabouzaid** [comment]
@vincentgiraud I've checked with the Operate team, and the var `GRAPHQL_PLAYGROUND_ENABLED` is actually a leftover and should not have any effect (thus, I will remove it in the next release)

Just to make sure this is not related to any other issues, did you try to set the env var `GRAPHQL_PLAYGROUND_ENABLED=false` and you had that error?

**Comment by aabouzaid** [comment]
@vincentgiraud it's already not there as mentioned in my previous reply.
I will remove the leftover vars soon (which don't have any effect anyway).

**Comment by aabouzaid** [comment]
Related task: #579

**Comment by vincentgiraud** [comment]
Thanks @aabouzaid, I just made the test following your recommandation "Just to make sure this is not related to any other issues". I understand it is a leftover but I still cannot log in into Tasklist ("session expired"). I'll close this issue since I can't reproduce on other cloud provider than Open Shift. So it may be just be something odd linked to how routes work in this particular environment.
