### ISSUE TITLE
[BUG] Helm chart for camunda-platform-8.1.0 went missing

### ISSUE THREAD

**Issue by mhuijgen** [camunda/camunda-platform-helm#456]
**Describe the bug:**

A few hours ago I could use the new helm chart version 8.1.0 (which at the time of writing this report was released 15h ago), but now it seems it got re-released 3h ago, but the .tgz package of the helm chart is missing.

**Actual behavior:**

helm install camunda camunda/camunda-platform
Error: INSTALLATION FAILED: failed to fetch https://github.com/camunda/camunda-platform-helm/releases/download/camunda-platform-8.1.0/camunda-platform-8.1.0.tgz : 404 Not Found

**Expected behavior:**

That helm can fetch the new chart from the https://helm.camunda.io repo

**Comment by mhuijgen** [comment]
I happened to have a tab open where the .tgz is still listed under the release:
![image](https://user-images.githubusercontent.com/48476507/197784619-8f54bcf6-7d64-4aa7-9c30-21414a2893c8.png)

But if I load the page now its gone:
![image](https://user-images.githubusercontent.com/48476507/197784701-7424e2b3-18b1-4a95-95c8-3d80ac8600db.png)

**Comment by mhuijgen** [comment]
Thanks for the reply.
I'll wait until it is fixed, was trying the new chart specifically for the external keycloak support.

**Comment by falko** [comment]
@aabouzaid is working on a fix

**Comment by aabouzaid** [comment]
It's been fixed, thanks for reporting it :+1:
