### ISSUE TITLE
[BUG] Cannot install version 8.1

### ISSUE THREAD

**Issue by hoangduy1912** [camunda/camunda-platform-helm#458]
**Describe the bug:**

I tried to upgrade 8.1 but got the following error. Same with fresh installation using default and custom values

Error: INSTALLATION FAILED: template: camunda-platform/charts/identity/templates/deployment.yaml:115:23: executing "camunda-platform/charts/identity/templates/deployment.yaml" at <include "identity.keycloak.url" .>: error calling include: template: camunda-platform/charts/identity/templates/_helpers.tpl:111:67: executing "identity.keycloak.url" at <$keycloakChart.Values.auth.tls.enabled>: invalid value; expected bool

**Environment:**
- Platform: microk8s
- Chart version: 8.1

Please let me know the solution. Thanks

**Comment by aabouzaid** [comment]
There is a bug in the C8 Helm chart v8.1.0, and I'm working on a fix shortly.

**Comment by aabouzaid** [comment]
This issue should be fixed.

If you still see an issue, remove the Helm cache before testing it again.

```
rm -rf ~/.helm/cache/archive/*
rm -rf ~/.helm/repository/cache/*
helm repo update
```

**Comment by hoangduy1912** [comment]
Thanks a lot @aabouzaid

It works now.
