### ISSUE TITLE
[BUG] <EKS Identity Helm issue>

### ISSUE THREAD

**Issue by satish8784** [camunda/camunda-platform-helm#460]
Installing Camunda 8 on EKS cluster gives below error 
Error: parse error at (camunda-platform/charts/identity/templates/_helpers.tpl:163): "-"

**Comment by aabouzaid** [comment]
Hi @satish8784 
Please use the [bug report template](https://github.com/camunda/camunda-platform-helm/issues/new?assignees=&labels=kind%2Fbug&template=bug_report_template.md&title=%5BBUG%5D+%3Cissue+title%3E) to provide all details about the issue.
Without much detail, it's hard to work on that issue.

**Comment by satish8784** [comment]
While trying to use latest Helm chart for installing Camunda platform 8 on AWS EKS cluster a parse error for identity pops up. Screenshot is attached.
![image](https://user-images.githubusercontent.com/25453707/198272485-de3ce13e-37a3-464e-aac2-04c5244596bc.png)


Helm installation does not begin due to parse error in identity/template/_helpers.tpl.
Helm installation should have started & deployed the Camunda pods.

Steps to reproduce:

-  Helm repo add https://helm.camunda.io/
-  helm install camunda8testrun camunda/camunda-platform -n camunda8


**Environment:**
AWS
Helm 3.5.4
Chart version -8.1.0
Default values
Kubernetes 1.23, Storage class gp3

**Comment by aabouzaid** [comment]
Looks like #464
Please use a newer Helm CLI version.
Not older than the one used in the repo here [.tool-versions](https://github.com/camunda/camunda-platform-helm/blob/c852472c0af62f760b3aa3cbdbe6f0d9acd3d110/.tool-versions#L1)

**Comment by satish8784** [comment]
That worked. Thanks @aabouzaid
