### ISSUE TITLE
[ENHANCEMENT] Documentation for configuring external/existing keycloak 

### ISSUE THREAD

**Issue by cruggieri** [camunda/camunda-platform-helm#461]
I've tried to install camunda with helm chart in a configuration with an existing keycloak, inside k8s or in en existing vm, without success.
It would be very useful to have a documentation on how to install camunda in this kind of situation. Up to now I had to figure out configurations taken from chart template, values helm files and so on.

Thank you

**Comment by aabouzaid** [comment]
Hi @cruggieri that totally makes sense, but I'm not sure about the time currently, I have many things on my plate at the moment.

However, what do you think about the following:
- You create an account on Camunda Platform [Community Slack](https://camunda-platform.slack.com/).
- I will support you there to make all changes needed to setup the external Keycloak.
- Then you create a guide for that in [camunda-platform-docs](https://github.com/camunda/camunda-platform-docs) (we already have [a couple of guides](https://github.com/camunda/camunda-platform-docs/tree/60929ff/docs/self-managed/platform-deployment/helm-kubernetes/guides) so it will be easy start and focus on the content ... which shouldn't be that big anyway).

What do you think?

**Comment by knottnhupfer** [comment]
Hi, have you been able to collect the informations? Is there a way get them or did you create a guide for it? Also struggling with the same problem.

Thx in advance

/david

**Comment by aabouzaid** [comment]
Yeah, actually, the guide has been there for some time (since v8.1 and now we are v8.2) but it looks like I missed closing this issue.

[Using Existing Keycloak](https://docs.camunda.io/docs/self-managed/platform-deployment/helm-kubernetes/guides/using-existing-keycloak/)
