### ISSUE TITLE
[ENHANCEMENT] upgrade Keycloak chart to support Keycloak 19

### ISSUE THREAD

**Issue by dlavrenuek** [camunda/camunda-platform-helm#465]
**Describe the use case:**

The helm chart included for Keycloak is uses the old 16.1.1 Keycloack version. The latest Keycloak version is 19.x and Identity already supports it starting from C8 version 8.1.0. The included Keycloak helm chart should be upgraded to support the latest version.

**Describe the enhancement/feature:**

Keycloak 16.1.1 has the `/auth` path hardcoded. In newer versions it can be configured and is `/` per default. To upgrade to the latest Keycloak helm chart you could either:

- set the environment variable `KEYCLOAK_HTTP_RELATIVE_PATH` to `/auth` on the Keycloak container

or 

- remove `/auth` when setting Keycloak URL in C8 applications or make the context path configurable. Some references of usage:
  - https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml#L107
  - https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/charts/identity/templates/deployment.yaml#L115
  - `camundaPlatform.issuerBackendUrl`

**Desired outcome and acceptance tests:**

When C8 is started with this helm chart
- [ ] the started Keycloak version is 19.x
- [x] I can login and use Identity
- [x] I can login and use Operate
- [x] I can login and use Optimize
- [x] I can login and use Tasklist
- [x] **BETA** I can login and use Web Modeler

**Comment by aabouzaid** [comment]
Github closed the issue automatically because I've mentioned it in #474 :D

**Comment by menski** [comment]
partial blocker to validate https://github.com/camunda/product-hub/issues/223 for one customer

**Comment by aabouzaid** [comment]
I've introduced the support for Keycloak v19 in #534 and everything looks working as expected :ok_hand: 
The last step is to change the version and that should be in the next minor release 8.2 (in April).

**Comment by aabouzaid** [comment]
@dlavrenuek as agreed, I will close this task since I already added a version change to [the next minor release checklist](https://github.com/camunda/camunda-platform-helm/issues/543).
