### ISSUE TITLE
Enable actuator endpoint usage-metrics by default

### ISSUE THREAD

**Issue by rob2universe** [camunda/camunda-platform-helm#469]
### What are try to solve
To ​​enable the usage metrics actuator endpoint in Operate and Tasklist API by default

**Describe the use case:**

The Operate documentation states the actuator enpoint,m which are enabled by default:
https://docs.camunda.io/docs/self-managed/operate-deployment/operate-configuration/#monitoring-operate

`management.endpoints.web.exposure.include: health, prometheus, loggers, usage-metrics, backup`

So these endpoint should be enabled by default and it should be possible to fetch the usage metrics by default.

For instance:
https://camunda.myexample.com/operate/actuator/usage-metrics/process-instances?startTime=1970-11-14T10:50:26.963-0100&endTime=2030-11-14T10:50:26.963-0100
should return the intended result by default.

The config map camunda-operate needs to be updated to include these default values.
Currently it includes: 
`management.endpoints.web.exposure.include: health,info,conditions,configprops,prometheus`

**Comment by aleksander-dytko** [comment]
The same should apply for Tasklist usage metrics, as currently it includes: `management.endpoints.web.exposure.include: health,info,conditions,configprops,prometheus`
