### ISSUE TITLE
[BUG] Cannot connect to zeebe from Modeler

### ISSUE THREAD

**Issue by hoangduy1912** [camunda/camunda-platform-helm#489]
**Describe the bug:**

I'm trying to connect to zeebe gateway from Camunda modeler but there's an error
![image](https://user-images.githubusercontent.com/11615917/203007903-f1501be4-b497-4831-b43f-8d7fcb7579ae.png)

I've checked camunda forum and found the following, which says zeebe should not be exposed.

(https://forum.camunda.io/t/camunda-self-managed-and-desktop-modeler-access/40201)

But from the camunda guide, it says

---
Once deployed, you can access the Camunda Platform 8 components on:

Web applications: https://camunda.example.com/[identity|operate|optimize|tasklist]
Keycloak authentication: https://camunda.example.com/auth
Zeebe Gateway: grpc://zeebe.camunda.example.com
---

So I'm wondering what's the best practice here and is it possible to connect to zeebe using ALB with a domain?

**Comment by aabouzaid** [comment]
@rob2universe wdyt about it? I think you have experience with Zeebe access from Modeler.

**Comment by rob2universe** [comment]
@hoangduy1912 - try to add the port number, e.g. `https://zeebe.....com:443`

**Comment by hoangduy1912** [comment]
@rob2universe 

Thank you for your feedback. I have tried but it didn't work. 

Here's my ingress detail

```
Name:             zeebe-gateway-ingress
Labels:           <none>
Namespace:        default
Address:         zeebe-gateway-alb-number.eu-central-1.elb.amazonaws.com
Ingress Class:    <none>
Default backend:  <default>
Rules:
  Host        Path  Backends
  ----        ----  --------
  *
              /*   camunda-zeebe-gateway:26500 (ipNumber:26500,ipNumber:26500)
Annotations:  alb.ingress.kubernetes.io/actions.ssl-redirect: true
              alb.ingress.kubernetes.io/backend-protocol: HTTPS
              alb.ingress.kubernetes.io/backend-protocol-version: GRPC
              alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:<awsNumber>:certificate/cert_id
              alb.ingress.kubernetes.io/healthcheck-path: /
              alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
              alb.ingress.kubernetes.io/load-balancer-name: zeebe-gateway-alb
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/tags: Name=zeebe-gateway-alb,Project=dev,Stage=dev
              alb.ingress.kubernetes.io/target-type: instance
              external-dns.alpha.kubernetes.io/hostname: zeebe.example.com
              kubernetes.io/ingress.class: alb
Events:
  Type    Reason                  Age   From     Message
  ----    ------                  ----  ----     -------
  Normal  SuccessfullyReconciled  8m1s  ingress  Successfully reconciled
```

**Comment by hoangduy1912** [comment]
Hi @rob2universe and @aabouzaid 

Can you help me to look into this problem?

**Comment by aabouzaid** [comment]
@hoangduy1912 did it work for you?

**Comment by hoangduy1912** [comment]
Thanks a lot @aabouzaid @rob2universe 

It worked just fine.
