### ISSUE TITLE
Invalid parameter - redirect uri

### ISSUE THREAD

**Issue by Premfer** [camunda/camunda-platform-helm#490]
Hi I am getting started with camunda8 in a on-prem k8s cluster using helm. I am trying to set identity also. Issue is I am getting the below error. I have installed all services of the operate , tasklist and optimize as Load balancer and have pointed them in Identity for appropriate root urls. Kindly let me know how to debug.

![image](https://user-images.githubusercontent.com/88700750/203124474-e788fbb5-e560-4775-890c-58e4cb2cb03a.png)

**Comment by aabouzaid** [comment]
@Premfer Please use the issue report template to be able to help.

**Comment by aabouzaid** [comment]
Closing this issue since a new one with more details is there #491.
