### ISSUE TITLE
[ENHANCEMENT] Upgrade PodDisruptionBudget from v1beta1 to v1

### ISSUE THREAD

**Issue by fvogl** [camunda/camunda-platform-helm#498]
In Kubernetes 1.25 some beta APIs have been removed and at least the PodDisruptionBudget policy/v1beta1 is used in the helm chart. Please release a new version which uses the GA APIs.

**Comment by aaabdallah** [comment]
This issue is blocking us as well for cronjobs: it is using batch/v1beta1 and it should now be upgraded to batch/v1

**Comment by MennaKhaled** [comment]
This is holding us back as well. Cronjobs disabled for now which is a big hassle.

**Comment by michelefa1988** [comment]
Can you please get a hotfix with these changes out? Pod Distibution budget needs to be disabled on 1.25.

**Comment by aabouzaid** [comment]
This has been fixed since v8.1.6, so I'm closing this issue.
