### ISSUE TITLE
[BUG] Elasticsearch indexes not reflecting after changes in values.yaml

### ISSUE THREAD

**Issue by ikomalchauhan** [camunda/camunda-platform-helm#502]
**Describe the bug:**

After changing the value at values.yaml, Zeebe Elasticsearch Exporter to create Elasticsearch indexes is not reflecting and showing the default value which is zeebe-record

**Actual behavior:**

not reflecting the records with the specified index label

**Expected behavior:**

if we change the value it should be reflecting the same

**How to reproduce:**

install helm chart with the change at line no 78 in values.yaml to some other value and then check the elastic search records in Kibana dashboard

**Logs:**

**Environment:**
- Platform: Azure
- Helm CLI version: v3.10.1
- Chart version: 8.1.2
- Values file:

**Comment by aabouzaid** [comment]
@ikomalchauhan Thank your for reporting the issue.

Please explicitly mention the parts with the issue and share any custom values files because the default file could be changed anytime.
