### ISSUE TITLE
Zeebe Record indices are not created.

### ISSUE THREAD

**Issue by Premfer** [camunda/camunda-platform-helm#517]
**Describe the issue:**

Hi, The issue I am facing is when installed in helm , though disable exporter is false in values.yaml, the zeebe record indices are not created in the ES. I checked this because I could not see process definitions and instances in the Operate. But I could see Operate Indices

Kindly advise which one to check.

**Comment by aabouzaid** [comment]
Please use the issue template so we can help with the issue.

**Comment by mary-grace** [comment]
@Premfer I see that you closed the issue yesterday. Were you able to fix the issue you experienced? If not, I'd like to hear more about your experience so we can improve it in the future.

**Comment by Premfer** [comment]
Hi @mary-grace I am uninstalling and reinstalling the camunda, so if still persists will create a new issue with issue template. Thanks
