### ISSUE TITLE
[ENHANCEMENT] Extra sidecar containers in all components

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda-platform-helm#518]
**Describe the use case:**

It can be very useful to quickly specify extra sidecar containers in deployments, as this allows one to colocate things like an OpenTelemetry sidecar exporter/collector (e.g. the OTLP bridge for Google Cloud Trace), agents monitoring your system, or even lightweight reverse proxies (e.g. for service meshes).

**Describe the enhancement/feature:**

I would like to be able to define additional extra sidecar containers in much the same way as the extra init containers.

**Desired outcome and acceptance tests:**

- Provide a way to add extra containers (aka `sidecar`) to all Camunda Platform 8 components.

**Comment by mimaom** [comment]
Great enhancement. I would also like that. Any plans on implementation?

BR
Michael
