### ISSUE TITLE
[ISSUE] When identity.keycloak.enabled is false, the camunda-platform ingress rule for keycloak shouldn't exist

### ISSUE THREAD

**Issue by upgradingdave** [camunda/camunda-platform-helm#530]
**Describe the issue:**

When `Set identity.keycloak.enabled` is set to false, the `camunda-platform` ingress should not include the rule routing traffic to an internal keycloak service (which doesn't exist). 

**Actual behavior:**

Here's the relevant section from `values.yaml`. The goal here is to install Camunda to point to an existing, external keycloak: 

```yaml
identity:
  keycloak:
    enabled: false
```

The `camunda-platform` ingress contains a rule for keycloak: 

```
Rules:
  Host                  Path  Backends
  ----                  ----  --------
  34.23.187.207.nip.io
                        /           camunda-keycloak-custom:443 (<error: endpoints "camunda-keycloak-custom" not found>)
```

**Expected behavior:**

When using this in the `values.yaml`: 

```yaml
identity:
  keycloak:
    enabled: false
```

The `camunda-platform` ingress should not contain a rule for keycloak. 

**How to reproduce:**

Set identity.keycloak.enabled to false, and then check the rules inside the camunda-platform ingress

**Logs:**

Here's a full output from the `camunda-platform` ingress: 

```
kubectl describe ingress
W0122 19:11:03.376201   76571 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
Name:             camunda-camunda-platform
Labels:           app=camunda-platform
                  app.kubernetes.io/instance=camunda
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=camunda-platform
                  app.kubernetes.io/part-of=camunda-platform
                  app.kubernetes.io/version=latest
                  helm.sh/chart=camunda-platform-8.1.5
Namespace:        camunda
Address:          34.23.187.207
Ingress Class:    nginx
Default backend:  <default>
TLS:
  tls-secret terminates 34.23.187.207.nip.io
Rules:
  Host                  Path  Backends
  ----                  ----  --------
  34.23.187.207.nip.io
                        /           camunda-keycloak-custom:443 (<error: endpoints "camunda-keycloak-custom" not found>)
                        /identity   camunda-identity:80 (10.12.0.42:8080)
                        /operate    camunda-operate:80 (10.12.0.38:8080)
                        /optimize   camunda-optimize:80 (10.12.0.40:8090)
                        /tasklist   camunda-tasklist:80 (10.12.0.41:8080)
Annotations:            cert-manager.io/cluster-issuer: letsencrypt
                        ingress.kubernetes.io/rewrite-target: /
                        meta.helm.sh/release-name: camunda
                        meta.helm.sh/release-namespace: camunda
                        nginx.ingress.kubernetes.io/ssl-redirect: false
Events:
  Type    Reason             Age                From                       Message
  ----    ------             ----               ----                       -------
  Normal  Sync               18m (x3 over 19m)  nginx-ingress-controller   Scheduled for sync
  Normal  CreateCertificate  18m                cert-manager-ingress-shim  Successfully created Certificate "tls-secret"
```

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: GCP
- Helm CLI version: 3.9.0
- Chart version: 8.1.5
- Values file: Here's a template I've tested with: [camunda-values-ext-keycloak.tpl.yaml](https://github.com/camunda-community-hub/camunda-8-helm-profiles/blob/main/keycloak/camunda-values-ext-keycloak.tpl.yaml)

**Comment by aabouzaid** [comment]
That's mainly used to access Keycloak internally if it's in Kubernetes but in another namespace.
But let me think if we should keep it or just remove that feature (to avoid complicating Camunda's Helm chart).

**Comment by upgradingdave** [comment]
Makes sense, thanks @aabouzaid . 

When I host Keycloak at a url like `https://keycloak.mydomain.com`, I need to set the `global.identity.keycloak.contextPath` to  `/` so the identity component can connect. 

But I think that has a side effect of creating the rule in the `camunda-platform` ingress to listen for traffic on `/`. Unfortunately, that rule seems to conflict with the `zeebe-gateway` ingress that also had a rule listening on `/` on the same ip address. 

So, ideally if you can have it so that the keycloak ingress rule is not created when the `identity.keycloak.enabled` is false would be nice. But to your point - if this introduces too much complexity, maybe we could add documentation to warn folks not to serve the zeebe gateway and keycloak on the same context path, or something along those lines?
