### ISSUE TITLE
[Enhancement, Connectors] Include element templates into web-modeler

### ISSUE THREAD

**Issue by igpetrov** [camunda/camunda-platform-helm#580]
**Describe the use case:**

Currently, the web-modeler pod does not include element templates.
This is a discoverability blocker.

**Describe the enhancement/feature:**

Connectors element templates are wired to the web-modeler.

**Desired outcome and acceptance tests:**

Once chart is deployed together with web-modeler and connectors, a user of the web-modeler should see available connectors from the element template list.

**Comment by igpetrov** [comment]
Pending follow up: https://github.com/camunda/product-hub/issues/582

**Comment by bastiankoerber** [comment]
we will use the marketplace in the near future to ship new OOTB Templates to the customer
