### ISSUE TITLE
[ISSUE] Not able to authenticate Optimize with an ES cluster with basic auth

### ISSUE THREAD

**Issue by krishnakumar797** [camunda/camunda-platform-helm#597]
**Describe the issue:**

Optimize application is throwing error while starting when it is connected to ES cluster with xpack basic authentication is configured. Tried with the below enviroment variables 

OPTIMIZE_ELASTICSEARCH_USERNAME
OPTIMIZE_ELASTICSEARCH_PASSWORD

Still its giving the error

```
Suppressed: org.elasticsearch.client.ResponseException: method [GET], host [http://elasticsearch-master:9200], URI [/_cluster/health?master_timeout=30s&level=cluster&timeout=30s], status line [HTTP/1.1 401 Unauthorized]
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/_cluster/health?master_timeout=30s&level=cluster&timeout=30s]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/_cluster/health?master_timeout=30s&level=cluster&timeout=30s]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}
```
This happens when I tried to deploy it using helm charts.

Optimize version: 3.9.4
Camunda version: 8.1.9
ES Version: 7.17.9

**Actual behavior:**

Getting ES authentication error while starting the Optimize application.

**Expected behavior:**

**How to reproduce:**

1) Deploy Optmize application using the helm chart connecting to Elastic Search with basic authentication configured.

**Logs:**

**Environment:**

- Platform:  Azure AKS Cluster
- Helm CLI version:  3.5.2
- Chart version: 8.1.7
- Values file:

**Comment by BobVanB** [comment]
Are your paramaters correct?
https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#optimize
| Name | Description |
|---|---|
| CAMUNDA_OPTIMIZE_ELASTICSEARCH_SECURITY_USERNAME	| The username for authentication in environments where a secured Elasticsearch connection is configured. |
| CAMUNDA_OPTIMIZE_ELASTICSEARCH_SECURITY_PASSWORD	| The password for authentication in environments where a secured Elasticsearch connection is configured. |

**Comment by aabouzaid** [comment]
Closing this since it will be fixed by https://github.com/camunda/camunda-platform-helm/pull/1356 in the next chart release v10.0.0.
