### ISSUE TITLE
helm chart does not deploy unless `webModeler.image.tag` is included

### ISSUE THREAD

**Issue by daniel-ewing** [camunda/camunda-platform-helm#612]
**Describe the issue:**

With the 8.1.x helm chart, I always included the `web-modeler.image.tag` because I frequently tried different versions.  With the 8.2.0 chart, if I do not include  `webModeler.image.tag`, thenthe chart does not deploy.  The reason seems to be that the configuration of `webModeler.image.pullSecrets[- name]` is not recognized.  See the two screenshots where the `- name` parameter is white vs orange.  Maybe this is just a problem from my IDE, but I don't think so...

![image](https://user-images.githubusercontent.com/73180349/231592970-501d32f5-8ac1-4bae-a941-30f4641aa516.png)
![image](https://user-images.githubusercontent.com/73180349/231593109-c82d128b-257b-44de-8eee-f013ae6f6c78.png)

**Actual behavior:**

When the helm chart is deployed, this error occurs:

Error: INSTALLATION FAILED: failed to parse /home/administrator/software/camunda/camunda-platform-8/daniel-ewing-camunda-platform-helm/dev/separate-ingress-tls-modeler-values.yaml: error converting YAML to JSON: yaml: line 89: mapping values are not allowed in this context

**Expected behavior:**

Helm chart is deployed

**How to reproduce:**

Try to deploy using my [values.yaml](https://github.com/daniel-ewing/camunda-platform-helm/blob/helm-deployment-fails/dev/separate-ingress-tls-modeler-values.yaml).

**Environment:**

- Platform: Minikube on Ubuntu Linux
- Helm CLI version: 3.10.1
- Chart version: 8.2.0
- Values file:  [values.yaml](https://github.com/daniel-ewing/camunda-platform-helm/blob/helm-deployment-fails/dev/separate-ingress-tls-modeler-values.yaml)

**Comment by daniel-ewing** [comment]
I found my mistake....

**Comment by aabouzaid** [comment]
@daniel-ewing what was it? :grinning:

**Comment by daniel-ewing** [comment]
@aabouzaid, look at the images above.  the `image` tag is indented below the `enabled` tag.

**Comment by aabouzaid** [comment]
@daniel-ewing in that case feel free to close the issue.
