### ISSUE TITLE
Web Modeler deployment error when using a current release version of C8, e.g.: 8.2.3

### ISSUE THREAD

**Issue by daniel-ewing** [camunda/camunda-platform-helm#626]
**Describe the issue:**

Web Modeler fails to deploy when using a current release version of C8, in your values.yaml, e.g.: `global.image.tag: 8.2.3`.  the issue is that in the main values.yaml [L1342](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml#L1342) `webModeler.image.tag` is not set by default.  We have released C8 versions 8.2.1, 8.2.2, and 8.2.3 but Web Modeler is still only version 8.2.0.  

**Actual behavior:**

Web Modeler does not deploy if using a current release version of C8, in your values.yaml, e.g.: `global.image.tag: 8.2.3`. 

**Expected behavior:**

Web Modeler should deploy regardless of `global.image.tag` value.

**Environment:**

- Platform: minikube
- Helm CLI version: 3.10.1
- Chart version: 8.2.0
- Values file: Use a values.yaml with:
`global.image.tag: 8.2.3`
`webModeler.image.tag` -- not set.

**Suggestion:**

Since Web Modeler release versions do not seem to be synchronized with the rest of the C8 versions, future helm chart versions should probably specify an actual value for `webModeler.image.tag`  and do not rely on the  `global.image.tag` value.

**Comment by aabouzaid** [comment]
The default behavior in the Helm chart is that WM has its own version, so to have that issue the user needs explicitly to unset the WM value so it will fail over the global value.

To avoid complicating the Helm chart template we will keep that behavior for now to be consistent.

**Comment by daniel-ewing** [comment]
Yes, thanks.  That is what the CHC have now.  If you look back to the version tag [8.2.0 L1342](https://github.com/camunda/camunda-platform-helm/blob/camunda-platform-8.2.0/charts/camunda-platform/values.yaml#L1342), for which this issue was reported, that was not previously the case.
