### ISSUE TITLE
[ISSUE] Update Keycloak values in the values file

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#646]
**Describe the issue:**

With CP 8.2 release, we moved to a newer Keycloak chart however, the CP8 values file still uses the older format under `identity.keycloak`.

**Actual behavior:**

CP8 values file uses the older Keycloak chart syntax, e.g. `identity.keycloak.auth.tls.enabled: true`.

**Expected behavior:**

CP8 values file should use (even for comments) the newer [Keycloak chart syntax](https://artifacthub.io/packages/helm/bitnami/keycloak/12.2.0), e.g. `identity.keycloak.auth.tls: true`.

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: Any
- Helm CLI version: 3.9.3
- Chart version: 8.2.2
- Values file: N/A

**Comment by mustafaelghrib** [comment]
Hi @aabouzaid I am interested in this issue and will try on my own to see if I could figure something

**Comment by mustafaelghrib** [comment]
@aabouzaid 
Did anyone fix this? I searched the repo for `identity.keycloak.auth.tls.enabled` but didn't find anything related, and according to https://artifacthub.io/packages/helm/bitnami/keycloak/12.2.0 it doesn't have `auth.tls` it uses `tls` directly and I see it implemented in this repo with no issue.

**Comment by aabouzaid** [comment]
@mustafaelghrib it would be great if you worked on this issue :rocket:

**Comment by mustafaelghrib** [comment]
Hi @aabouzaid I may need some guidance

**Comment by aabouzaid** [comment]
@mustafaelghrib feel free to ask any question.

**Comment by mustafaelghrib** [comment]
> @aabouzaid Did anyone fix this? I searched the repo for `identity.keycloak.auth.tls.enabled` but didn't find anything related, and according to https://artifacthub.io/packages/helm/bitnami/keycloak/12.2.0 it doesn't have `auth.tls` it uses `tls` directly and I see it implemented in this repo with no issue.

**Comment by aabouzaid** [comment]
@mustafaelghrib We are using Keycloak as a [dependency for Identity](https://github.com/camunda/camunda-platform-helm/blob/2c27fb9aa727386ac487374deab9eeb0f86c9cf0/charts/camunda-platform/charts/identity/Chart.yaml#L7). So all vars under the key `identity.keycloak` is passed to [Keycloak 12.3.0 chart](https://artifacthub.io/packages/helm/bitnami/keycloak/12.3.0) (you can see the [chart version in Identity Chart.yaml file](https://github.com/camunda/camunda-platform-helm/blob/2c27fb9aa727386ac487374deab9eeb0f86c9cf0/charts/camunda-platform/charts/identity/Chart.yaml#L10C14-L10C20)) (that also means you will not see that key in this repo).

What you mentioned is the actual issue we need to fix. We need to ensure that all vars in the Camunda repo are actually used in Keycloak chart.

So `identity.keycloak.auth.tls.enabled` is wrong, it should be `identity.keycloak.tls.enabled` because if we checked  [Keycloak 12.3.0 chart values](https://artifacthub.io/packages/helm/bitnami/keycloak/12.3.0), you will not find it and we need to change that in Camunda's values file.

I hope that clarifies the issue we are trying to solve here. But always feel free to ask.

**Comment by HamzaMasood1** [comment]
I have confirmed that all keycloak values seem to be updated based on the 12.3.0 chart.  Therefore this issue can be closed.
