### ISSUE TITLE
[ISSUE] connectors enabled by default despite README

### ISSUE THREAD

**Issue by nhomble** [camunda/camunda-platform-helm#648]
**Describe the issue:**

The README states that the `connectors` are disabled by default. This seems to disagree with source: https://github.com/camunda/camunda-platform-helm/blame/main/charts/camunda-platform/values.yaml#L1760

**Actual behavior:**

The connectors container is getting pulled.

**Expected behavior:**

I don't expect any connectors container in the deployment.

**How to reproduce:**

helm deploy vanilla chart

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:

**Comment by aabouzaid** [comment]
Hi @nhomble :wave: 
Thanks for reporting this :+1: 

It's actually the other way around. So I've updated the readme file.
