### ISSUE TITLE
Inconsistency with Zeebe gateway defaults

### ISSUE THREAD

**Issue by jothikiruthika** [camunda/camunda-platform-helm#695]
**Describe the issue:**

By default, [the authentication at the gateway is none](https://github.com/camunda/zeebe/blob/main/dist/src/main/config/gateway.yaml.template#L160-L165). But when installing a Camunda 8 instance with helm charts, the [default value for authentication is set to identity](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml#L77-L78). This gets confusing, as the official documentation states that the [default behaviour is - Authentication - none](https://docs.camunda.io/docs/self-managed/zeebe-deployment/security/client-authorization/#gateway).

**Actual behavior:**

When I install a gateway node using helm charts, the ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE env variable is set to identity.

**Expected behavior:**

The value of ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE should be none, consistent with Zeebe's defaults.

- Platform: Camunda 8.2.0 & above

**Comment by korthout** [comment]
Alternatively, the documentation should be adjusted to clarify the difference.

**Comment by aabouzaid** [comment]
@jothikiruthika thanks for opening this PR.
The auth is meant to be enabled by default for all components in the Camunda Platform 8 Helm chart.
So I've created a PR to update the docs accordingly - https://github.com/camunda/camunda-platform-docs/pull/2157

**Comment by aabouzaid** [comment]
I'm closing this issue since the docs PR is merged.

And for the records, the Zeebe Gateway auth could be disabled by setting:

```
zeebe-gateway:
  env:
  - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
    value: "none"
```
