### ISSUE TITLE
[ISSUE] Avoid leaking secrets via logs by printing out all the environment in Zeebe

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda-platform-helm#711]
**Describe the issue:**

When starting a Zeebe broker, it seems we print out all the environment variables. This can leak secrets to the logs. See https://github.com/camunda/camunda-platform-helm/blob/dae5ca121777837ab9e068b3085ac4ab89856292/charts/camunda-platform/charts/zeebe/templates/configmap.yaml#L20

**Actual behavior:**

If you deploy Zeebe via the chart, the brokers will print out their environments to STDOUT.

**Expected behavior:**

No secrets are leaked, and the environment is not printed, or it's printed behind a conditional, opt-in debug flag.

**How to reproduce:**

Deploy Zeebe without overwriting the startup script injected by the Helm chart, and look at the logs.

**Logs:**

```
+ export ZEEBE_BROKER_CLUSTER_NODEID=0
+ ZEEBE_BROKER_CLUSTER_NODEID=0
++ ls -A /exporters/
+ '[' '' ']'
+ echo 'No exporters available.'
+ env
No exporters available.
KUBERNETES_SERVICE_PORT_HTTPS=443
ZEEBE_LOG_LEVEL=info
KUBERNETES_SERVICE_PORT=443
HOSTNAME=dev-zeebe-0
LANGUAGE=en_US:en
JAVA_HOME=/opt/java/openjdk
...more
```

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: any
- Chart version: 8.2.4

Relates to https://jira.camunda.com/browse/SUPPORT-17050

**Comment by megglos** [comment]
@aabouzaid this may also need backporteding to 8.1/8.0 if these are still maintained.
