### ISSUE TITLE
[TASK] Add Elastic credentials to global properties

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda-platform-helm#726]
Epic:  https://github.com/camunda/camunda-platform-helm/issues/473

**Describe the use case:**

When authentication is enabled on Elasticsearch we need to provide 4 env vars for Operate:
```
CAMUNDA_OPERATE_ELASTICSEARCH_USERNAME
CAMUNDA_OPERATE_ELASTICSEARCH_PASSWORD
CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_USERNAME
CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_PASSWORD
```
The same for Tasklist and probably also Optimize.

**Describe the enhancement/feature:**

Ideally we define username/password pair only once in `global` properties and reuse in all components.

**Desired outcome and acceptance tests:**

**Comment by aabouzaid** [comment]
Closing this since it will be fixed by https://github.com/camunda/camunda-platform-helm/pull/1356 in the next chart release v10.0.0.
