### ISSUE TITLE
[ENHANCEMENT] Add Ingress details into NOTES.txt

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#736]
**Describe the enhancement/feature:**

Currently, we don't have the Ingress details in [NOTES.txt](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/templates/NOTES.txt). It would be helpful to have the URLs for combined and separated Ingress setup. 

**Desired outcome and acceptance tests:**

- Conditionally add Ingress URLs into NOTES.txt for combined and separated Ingress setup.

Fixed by: https://github.com/camunda/camunda-platform-helm/pull/749

**Comment by mstva** [comment]
@aabouzaid where to find those Ingress URLs?

**Comment by aabouzaid** [comment]
@mstva in the [values file](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml) under `global.ingress.host` in case of the [combined Ingress setup](https://docs.camunda.io/docs/next/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup/#combined-ingress-setup).

or under `[APP_NAME].ingress.host` in case of the [separated Ingress setup](https://docs.camunda.io/docs/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup/#separated-ingress-setup).

**Comment by aabouzaid** [comment]
This was fixed by: https://github.com/camunda/camunda-platform-helm/pull/749
