### ISSUE TITLE
[ISSUE] <INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating 

### ISSUE THREAD

**Issue by sheteshruti** [camunda/camunda-platform-helm#765]
**Describe the issue:**
I'm trying deploy zeebe and its releated components like operate and elasticsearch.
If I disable any other component like tasklist I get below error :
INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.volumeClaimTemplates[0].spec.accessModes): invalid type for io.k8s.api.core.v1.PersistentVolumeClaimSpec.accessModes: got "string", expected "array"

**Actual behavior:**

If all the components are enabled kubectl deploys all the compenets.
not able to disable tasklist, optimize etc

**Expected behavior:**
Should deploy only zeebe and its releated components

**How to reproduce:**
disable tasklist from values.yaml

**Comment by aabouzaid** [comment]
Hi @sheteshruti, Please use the issue template ... a lot of info is missing here.
