### ISSUE TITLE
[ISSUE] The default value of `retentionPolicy.zeebeIndexTTL` is much too small!

### ISSUE THREAD

**Issue by daniel-ewing** [camunda/camunda-platform-helm#774]
**Describe the issue:**

The default value is `retentionPolicy.zeebeIndexTTL: 1` - [line 1098](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml#L1098).

**Actual behavior:**

When index cleanup is enabled by setting `retentionPolicy.enabled: true` - [line 1094](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml#L1094), then by default, Zeebe indices start getting deleted after 1 day.  This value is unrealistic.  It does not give the platform users any time at all to:
-  Realize there is some problem with Zeebe data import into Operate.
- Course correct by increasing the value and deploying the change.

**Expected behavior:**

The default value should be much larger.  At least `7` and `14` would be better.  A value of `1` might be acceptable in a development environment, but it is absolutely not acceptable for testing / production, so it should not be the default.

**How to reproduce:**

N/A.

**Logs:**

N/A.

**Environment:**

N/A.

**Comment by jessesimpson36** [comment]
related : https://github.com/camunda/camunda-platform-helm/issues/800

**Comment by daniel-ewing** [comment]
@jessesimpson36, my bad, go ahead and close this as a duplicate if you want.
