### ISSUE TITLE
Unable to get Camunda running with restricted SecurityContext settings

### ISSUE THREAD

**Issue by jothikiruthika** [camunda/camunda-platform-helm#795]
**Describe the issue:**

As a security best practise, many enterprises mandate that a few SecurityContext settings be leveraged, so that containers don't run with unintended privileges, which could pave way for security issues. 

Setting the below in the security context, we are facing issues in bringing the pods up -

```
privileged: false
readOnlyRootFilesystem: true
allowPrivilegeEscalation: false
runAsNonRoot: true
runAsUser: 1000
```

**Actual behavior:**

When the readOnlyRootFilesystem is set to true almost all the pods, report issues of unable to access certain files on the root file system and the pods don't come up as ready.

we need to create EmptyDir Volumes and mount them in the expected path, and use extraInitContainers to copy over the required files to this mounted volume , so that the pods get ready.

**Expected behavior:**

The Camunda application should be working and all the pods should come up as ready, even with the securityContext restrictions applied, without having to mount the data volumes and copying the required files/folders using the initcontainers.

This is a requirement in multiple enterprise Kubernetes environments, from the security perspective. 

**How to reproduce:**

Attached is the values.yaml file used to install camunda using the helm charts.

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: Applicable to all environments, but we tested on azure.
- Helm CLI version: v3.9.4
- Chart version: 8.2.8  
- Values file:  [Values File Sample](https://github.com/jothikiruthika/CamundaOnSecureEnvironment/blob/main/values.yaml)

Related: [SUPPORT-17740](https://jira.camunda.com/browse/SUPPORT-17740)

**Comment by jessesimpson36** [comment]
Discussed in backlog grooming session regarding the readOnlyFilesystem option:

We want application teams to in some way provide us with the directory paths that their components write to. For Zeebe / Tasklist, and such, one proposal is for them to use `VOLUME` inside their Dockerfiles to indicate to us that their docker image writes to that particular directory. 

In the case of Elasticsearch, Keycloak, and Postgresql,  we believe that application teams need to communicate these component's directories to us as well. One concern I have about that idea is that application teams may not have the knowledge necessary to know what directories that Keycloak writes to.  In this case, we discussed communicating this with Identity team via a training, or for Identity team to work in collaboration with Infra team to get a tool that can monitor the write operations.

**Comment by jessesimpson36** [comment]
Also relevant: https://github.com/camunda/product-hub/issues/717

**Comment by aabouzaid** [comment]
I am closing this since the change has been merged in https://github.com/camunda/camunda-platform-helm/pull/864, and it will be part of v8.3.0.
