### ISSUE TITLE
[TASK] Add support for automountServiceAccountToken

### ISSUE THREAD

**Issue by jothikiruthika** [camunda/camunda-platform-helm#796]
**Describe the use case:**

As a security best practise, many enterprises require the automountServiceAccountToken to be set to false. It is preferred to have them driven from the Camunda helm charts. Without the support for this flag from the helm charts, teams have to apply this setting as a patch to the individual deployments / statefulsets. This becomes an overhead from a maintenance perspective. 

**Describe the enhancement/feature:**

Add support for automountServiceAccountToken property of Kubernetes pods, in Camunda helm charts.

**Desired outcome and acceptance tests:**

We should be able to set automountServiceAccountToken to false for all the camunda pods, from the values.yaml file.

**Comment by jessesimpson36** [comment]
Ahmed mentioned a concern at one point that we need to be careful about the k8s api version since automountServiceAccountToken  is a fairly recent option.  

I also think this is related to the overarching product-hub ticket https://github.com/camunda/product-hub/issues/1430
