### ISSUE TITLE
[ISSUE] The default value of `zeebeIndexTTL` is much too small

### ISSUE THREAD

**Issue by daniel-ewing** [camunda/camunda-platform-helm#800]
**Describe the issue:**

The [default value](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml#L1098) of `zeebeIndexTTL` is `1`.  if `retentionPolicy.enabled: true` is configured any user might simply trust that this default value is already set to a reasonable value.

**Actual behavior:**

This value is not reasonable.  In an environment that is busy, or one where either Operate or Optimize importers are lagging just a little, or where there is a problem with one of the importers for some reason, it would be trivially easy to lose Zeebe data.

**Expected behavior:**

The default value should be reasonably configured to prevent data loss and environment corruption. 

**Related**

[SUPPORT-17371](https://jira.camunda.com/browse/SUPPORT-17371)

**Comment by aabouzaid** [comment]
We will keep the value now to avoid any behavior change in the released versions.
But feel free to open this issue again if we need bigger issues related to the TTL.
