### ISSUE TITLE
[ISSUE] Centralised Logging Failing for Zeebe on EFK Stack

### ISSUE THREAD

**Issue by shahamit** [camunda/camunda-platform-helm#803]
**Describe the issue:**

We have EFK (elasticsearch, fluentd and kibana) in our centralised logging stack. We need to ship zeebe broker and gateway logs to this stack for troubleshooting and debugging purposes. To do so we enabled `google stackdriver` for [json](https://docs.camunda.io/docs/8.1/self-managed/zeebe-deployment/configuration/logging/#google-stackdriver-json-logging) logging but still we don't see the zeebe logs on kibana

**Actual behavior:**

On troubleshooting the issue we found that fluentd fails to push the zeebe logs to elasticsearch and reports an error that states
```
Could not push log to Elasticsearch: {"took"=>7, "errors"=>true, "items"=>[{"index"=>{"_index"=>"efk-stack-dev-zeebe-0-2023.07.20", "_id"=>"g2CHcokBGuA_evY3KWVK", "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"can't merge a non object mapping [kubernetes.labels.app] with an object mapping"}}}
```
The root cause here looks to be the label `app` added by the helm chart [here](https://github.com/camunda/camunda-platform-helm/blob/d00dc6c6518d5108f384cbc700b54fa8053bc44c/charts/camunda-platform/values.yaml#L31).

We hacked into the runtime deployment and removed the `app` label for the broker statefulset component and found the logs were getting shipped from fluentd to elasticsearch. 

**Expected behavior:**

All the logs from all brokers and gateway replicas should be shipped to elasticsearch so that they can be viewed centrally through kibana UI along with logs from other architectural components.

**How to reproduce:**

1. Deploy EFK stack 
2. Enable stackdriver for zeebe broker and gateway
3. View the fluentd logs for errors (reported above)

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: any deployment including local
- Helm CLI version: 3.10.0
- Chart version: 8.2.0

This issue is important because this will enable zeebe workflow engine to integrate with the standard logging stack (EFK) so that logs are centralised which enables troubleshooting and monitoring of the platform.

**Comment by shahamit** [comment]
@Zelldon @falko @aabouzaid - any help on this issue?

**Comment by shahamit** [comment]
Apparently the issue is with the `app` label. If we remove it the logs get pushed to elasticsearch. The only problem remains is removing the `app` label from the values.yaml file.

 I tried setting them null both in the values.yaml and in the helm install command but it didn't help.

```yaml
global:
  labels:
    app: null
```
`helm install dev camunda/camunda-platform -f camunda-local.yaml --set global.labels.app=null`

Any idea why the `app` label is not getting set to null?

Thanks.

**Comment by aabouzaid** [comment]
@shahamit I didn't dig inside null labels doesn't work, but Helm already has a couple of issues related to nulling values.
So I'd suggest using [Helm post-rendering](https://helm.sh/docs/topics/advanced/#post-rendering), or even filtering the logs before sending the data to ES using Fluentd.

It's out of the scope of the chart itself, so I'm closing this issue.
