### ISSUE TITLE
[ISSUE] Resetting podAntiAffinity not possible

### ISSUE THREAD

**Issue by floric** [camunda/camunda-platform-helm#816]
**Describe the issue:**

We have multiple (more than 8) Camunda Platforms running in one namespace (used for isolated dev instances). Each Zeebe and Zeebe Gateway runs with only one replica (no high availability needed), except one central instance in the same namespace with the default number of replicas (2 and 3). Unfortunately running too many Camunda Platforms in the same namespace leads to conflicts caused by the default affinity values used for Zeebe and its gateway. It's not possible any more to find nodes where no zeebe-broker/zeebe-gateway is already running. So the scheduling fails because of the affinity properties of Zeebe and the gateway.

**As we don't replicate anyway for these dev instances, we simply wanted to disable the affnity property completely (or configure it in a way that it doesn't influence scheduling of these separated environments by taken the release name into consideration).**

Unfortunately each try to reset the affinity property failed.

**Actual behavior:**

We tried the following properties

`camunda-platform.zeebe.affinity={}`

`camunda-platform.zeebe.affinity=null`

`camunda-platform.zeebe.affinity.podAntiAffinity={}`

`camunda-platform.zeebe.affinity.podAntiAffinity=null`

setting in the `values.yaml` (complete overwrite with other values or resetting with empty values or using `--set camunda-platform...=<val>`.

Unfortunately no try t o reset the affinity to schedule nodes freely succeeded.

We even tried to deeply overwrite the label selector with:
` --set 'camunda-platform.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].labelSelector.matchExpressions[0].values[0]=zeebe-broker-something-else'`

But even this had no effect at all.

**Expected behavior:**

Resetting or at least disabling the affinity should be possible for our usecase to run many isolated temporary Camunda platforms with reduced resources.

**How to reproduce:**

Try setting:

`camunda-platform.zeebe.affinity={}`

`camunda-platform.zeebe.affinity=null`

`camunda-platform.zeebe.affinity.podAntiAffinity={}`

`camunda-platform.zeebe.affinity.podAntiAffinity=null`

 `'camunda-platform.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].labelSelector.matchExpressions[0].values[0]=zeebe-broker-something-else'`

The unit tests in this project add only additional constraints to `affinity`. This is unfortunately different to manually removing existing affinity settings.

**Environment:**

- Platform: AWS EKS
- Helm CLI version: 3
- Chart version: 8.2.10

**Comment by daniel-ewing** [comment]
Hi @floric,

Since you resolved this on your own, do you want to share your findings here, in case someone else has this issue?

**Comment by floric** [comment]
Good news. The issue somehow must be caused by Helm. After a lot of hours of experiments I finally found for Helm 3.10+ (support for set-json) the following working solution:

```
--set-json=camunda-platform.zeebe.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution=[]
--set-json=camunda-platform.zeebe-gateway.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution=[]
```
 
The same also works in the values.yaml:

```
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: [] 
```

I still don't know why Helm behaves so weird, but at least this works for us resulting in the following spec for all pods:

```
affinity:
  podAntiAffinity: {}
```
