### ISSUE TITLE
[ISSUE] ES is not bumped to latest patch level in value files

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-platform-helm#876]
**Describe the issue:**

ES is not bumped to latest patch level in value files.

**Actual behavior:**

* See that current version is [`7.17.10`](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values/values-latest.yaml#L50)

**Expected behavior:**

* Latest is [`7.17.13`](https://github.com/elastic/elasticsearch/releases/tag/v7.17.13)
* Renovate should provide respective PR

**How to reproduce:**

View https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values/values-latest.yaml#L50

**Logs:**

n/a

**Environment:**

n/a

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:

**Comment by aabouzaid** [comment]
@MaxTru thank you for reporting that.

There was an issue with matching as the ES image uses the Elastic Docker registry.
It has been fixed in #877, and #879 is the Renovate PR for ES.
